[add] Manage page of Activity Organization
kaiyuanshe/OpenHackathon-Web pull request #113
Opened 2022-10-03 17:57 UTC by wangrunlin

- [add] Manage page of Activity Organization #108

2022-10-13 06:13 UTC, stevending1st commented on models/Organization.ts
> +};
`Enum` 是不是好点。

2022-10-13 06:13 UTC, stevending1st commented on pages/activity/[name]/manage/organization.tsx
> +            {typeCount.host ? typeCount.host : 0}
```suggestion
            {typeCount.host || typeCount.host}
```

2022-10-13 06:13 UTC, stevending1st commented on pages/activity/[name]/manage/organization.tsx
> +            {allItems.length - (typeCount.host ? typeCount.host : 0)}
```suggestion
            {allItems.length - (typeCount.host || 0)}
```

2022-10-13 06:13 UTC, stevending1st commented on pages/activity/[name]/manage/organization.tsx
> +          onSave={() => (this.show = false) || this.store.refreshList()}
这里会一直返回 `false`，不会触发 `this.store.refreshList()`。

2022-10-13 06:17 UTC, wangrunlin commented on components/Organization/ActivityOrganizationModal.tsx
> +
一些之后有可能会添加的字段
这些注释还是可以删除的
等待将来需要再添加

2022-10-13 06:20 UTC, wangrunlin commented on pages/activity/[name]/manage/organization.tsx
> +          onSave={() => (this.show = false) || this.store.refreshList()}
那这里直接运行 `this.store.refreshList()` 可以吗？

2022-10-13 06:23 UTC, stevending1st commented on pages/activity/[name]/manage/organization.tsx
> +          onSave={() => (this.show = false) || this.store.refreshList()}
> 那这里直接运行 `this.store.refreshList()` 可以吗？

可以在 `this.store.refreshList()` 内设置 `this.show` 为 `false`。

2022-10-13 06:24 UTC, wangrunlin commented on models/Organization.ts
> +};
确实是
不过我在使用 Enum 的过程中不太会使用 TypeScript 的 Enum 类型以字符串作为键的这种用法

我再查阅一下文档尝试一下

2022-10-13 06:27 UTC, wangrunlin commented on pages/activity/[name]/manage/organization.tsx
> +          onSave={() => (this.show = false) || this.store.refreshList()}
OK 了解了

多谢建议

2022-10-13 17:06 UTC, TechQuery commented on pages/activity/[name]/manage/organization.tsx
> +          onSave={() => (this.show = false) || this.store.refreshList()}
> > 那这里直接运行 `this.store.refreshList()` 可以吗？
> 
> 可以在 `this.store.refreshList()` 内设置 `this.show` 为 `false`。

不建议将视图状态放在 store 中控制，就在本组件内自己控制。

2022-10-13 17:07 UTC, TechQuery commented on pages/activity/[name]/manage/organization.tsx
> +          onSave={() => (this.show = false) || this.store.refreshList()}
@wangrunlin 这里写的没问题，无需修改

2022-10-13 17:39 UTC, TechQuery requested changes

2022-10-13 17:39 UTC, TechQuery commented on components/Organization/ActivityOrganizationModal.tsx
> +      >(currentTarget);
```suggestion
    const { store, onSave } = this.props;

    const { name, description, type, logoURI } =
      formToJSON<
        Pick<OrganizationForm, 'name' | 'description' | 'type' | 'logoURI'>
      >(event.currentTarget);
```

2022-10-13 17:39 UTC, TechQuery commented on components/Organization/ActivityOrganizationModal.tsx
> +          <Form
```suggestion
        <Modal.Body as="form"
```

2022-10-13 17:39 UTC, TechQuery commented on components/Organization/ActivityOrganizationModal.tsx
> +                  },
```suggestion
                  ([key, value]) => (
                      <option key={key} value={key}>
                        {value}
                      </option>
                    ),
```
组件引擎渲染列表的 `key` 尽量与顺序无关

2022-10-13 17:39 UTC, TechQuery commented on components/Organization/ActivityOrganizationModal.tsx
> +              <Button variant="primary" type="submit" id="increase">
```suggestion
              <Button variant="primary" type="submit">
```

2022-10-13 17:39 UTC, TechQuery commented on components/Organization/ActivityOrganizationModal.tsx
> +  increaseId = async (event: FormEvent<HTMLFormElement>) => {
方法命名表意有误

2022-10-13 17:39 UTC, TechQuery commented on models/Organization.ts
> +}
```suggestion
import { Media } from './Base';

export enum OrganizationType {
  Host = 'host'.
  Organizer = 'organizer',
  Coorganizer = 'coorganizer',
  Sponsor = 'sponsor',
  TitleSponsor = 'titleSponsor',
}

export const OrganizationTypeName = {
  [OrganizationType.Host]: '主办',
  [OrganizationType.Organizer]: '承办',
  [OrganizationType.Coorganizer]: '协办',
  [OrganizationType.Sponsor]: '赞助',
  [OrganizationType.TitleSponsor]: '冠名',
};

export interface Organization extends Base {
  name: string;
  description?: string;
  type: OrganizationType;
  logo?: Media;
}
```

2022-10-13 17:39 UTC, TechQuery commented on models/Organization.ts
> +  indexKey = 'id' as const;
```suggestion
```
基类默认值无需重复声明

2022-10-13 17:39 UTC, TechQuery commented on models/Organization.ts
> +    const { body } = await this.client.put<Organization>(this.baseURI, data);
```suggestion
  async updateOne(data: NewData<Organization>, id?: IDType) {
    const { body } = await (id
        ? this.client.patch<Organization>(`${this.baseURI}/${id}`, data)
        : this.client.put<Organization>(this.baseURI, data)
    );
```
修改也一起做了吧

2022-10-13 17:39 UTC, TechQuery commented on components/Organization/OrganizationList.tsx
> +                    const index = selectedIds.indexOf(id);
```suggestion
                    if (checked) return onSelect([...selectedIds, id]);

                    const index = selectedIds.indexOf(id);
```

2022-10-13 17:39 UTC, TechQuery commented on components/Organization/OrganizationList.tsx
> +                    logo?.description === null ? description : logo.description
```suggestion
                    logo?.description || description
```
（下同）

2022-10-13 17:39 UTC, TechQuery commented on pages/activity/[name]/manage/organization.tsx
> +  store = activityStore.organizationOf(this.props.name);
合并主分支后，路由取参数的方式会简化，参考：
https://github.com/kaiyuanshe/OpenHackathon-Web/blob/b442bd301fbf796d77f777d3c11f600c5e019768/pages/activity/%5Bname%5D/manage/participant/index.tsx#L13-L19

2022-10-13 17:39 UTC, TechQuery commented on pages/activity/[name]/manage/organization.tsx
> +            {typeCount.host || typeCount.host}
```suggestion
            {typeCount.host || 0}
```

2022-10-13 17:39 UTC, TechQuery commented on pages/activity/[name]/manage/organization.tsx
> +            <Col sm="auto" md="auto">
```suggestion
          <Row xs={1} sm={2}>
            <Col>
```

2022-10-13 17:39 UTC, TechQuery commented on pages/activity/[name]/manage/organization.tsx
> +                <Button variant="danger" type="submit" id="delete">
```suggestion
                <Button variant="danger" type="submit">
```

2022-10-13 17:39 UTC, TechQuery commented on pages/activity/[name]/manage/organization.tsx
> +              </div>
```suggestion
                <OrganizationList
                  store={store}
                  onSelect={list => (this.selectedIds = list)}
                />
```

2022-10-14 06:02 UTC, TechQuery requested changes

2022-10-14 06:02 UTC, TechQuery commented on pages/activity/[name]/manage/organization.tsx
> +import { OrganizationModal } from '../../../../components/Organization/ActivityOrganizationModal';
```suggestion
import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next';
import { observable } from 'mobx';
import { observer } from 'mobx-react';
import { FormEvent, PureComponent } from 'react';
import { Badge, Button, Col, Form, ListGroup, Row } from 'react-bootstrap';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faPlus, faTrash } from '@fortawesome/free-solid-svg-icons';

import PageHead from '../../../../components/PageHead';
import { ActivityManageFrame } from '../../../../components/Activity/ActivityManageFrame';
import { OrganizationList } from '../../../../components/Organization/OrganizationList';
import { OrganizationModal } from '../../../../components/Organization/ActivityOrganizationModal';

import activityStore from '../../../../models/Activity';
```

2022-10-14 06:02 UTC, TechQuery commented on pages/activity/[name]/manage/organization.tsx
> +        <PageHead title={`${name} 活动管理 主办方`} />
```suggestion
      <ActivityManageFrame path={path} name={name} title="主办方管理">
```

2022-10-14 08:57 UTC, TechQuery requested changes

2022-10-14 08:57 UTC, TechQuery commented on components/Organization/OrganizationList.tsx
> +import styles from '../../styles/Table.module.less';
```suggestion
import { observer } from 'mobx-react';
import { Form, Image, Table } from 'react-bootstrap';

import { ScrollList, ScrollListProps } from '../ScrollList';
import styles from '../../styles/Table.module.less';
import {
  Organization,
  OrganizationModel,
  OrganizationTypeName,
} from '../../models/Organization';
```

2022-10-14 08:59 UTC, TechQuery approved these changes

2022-10-14 09:01 UTC, merged