团队后台/团队报名/团队权限管理/报名/退出/我的团队/其他优化
kaiyuanshe/OpenHackathon-Web pull request #114
Opened 2022-10-05 06:58 UTC by stevending1st

Checklist（清单）:

- [x] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #99

2022-10-14 06:32 UTC, TechQuery requested changes

2022-10-14 06:32 UTC, TechQuery commented on components/Team/TeamAdministratorTable.tsx
> +    },
```suggestion
    onUpdateRole: (userId, role) => this.store.updateRole(userId, role),
```
（下同）

2022-10-14 06:32 UTC, TechQuery commented on components/Team/TeamAdministratorTable.tsx
> +              return (
省略 `{ return }`

2022-10-14 06:32 UTC, TechQuery commented on components/Team/TeamAdministratorTable.tsx
> +                    idx === 7 ? (
```suggestion
                  ].map((data, idx, { length }) =>
                    idx + 1 === length ? (
```
（下同）

2022-10-14 06:32 UTC, TechQuery commented on components/Team/TeamAdministratorTable.tsx
> +                      <td key={idx + userId}>
```suggestion
                      <td key={userId}>
```
不到万不得已，`key` 不和数组下标绑定。（下同）

2022-10-14 06:32 UTC, TechQuery commented on components/Team/TeamManageFrame.tsx
> +      this.isLoading = false;
store 上的 `downloading` 属性不能做加载状态控制吗？

2022-10-14 06:32 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/index.tsx
> +    const { user } = sessionStore;
```suggestion
    if (isServer()) return;

    const { name } = this.props.activity,
        { user } = sessionStore;
```

2022-10-14 06:32 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/index.tsx
> +        : undefined;
```suggestion
      this.currentUserInThisTeam = user?.id
        && await this.store.getOne(user.id);
```

2022-10-14 06:32 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/index.tsx
> +        : '';
```suggestion
      this.teamMemberRole = this.currentUserInThisTeam?.role || '';
```

2022-10-14 06:32 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/index.tsx
> +      }
```suggestion
      const { status } = error as ErrorBaseData;

      if (status !== 404) this.teamMemberRole = '';
```

2022-10-14 06:32 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/index.tsx
> +    const { isShowJoinReqModal, handleJoinTeam } = this;
```suggestion
    ],
    { isShowJoinReqModal, handleJoinTeam } = this;
```

2022-10-14 06:32 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/index.tsx
> +            <Form onSubmit={handleJoinTeam}>
```suggestion
          <Modal.Body as="f
orm" onSubmit={handleJoinTeam}>
```

2022-10-14 08:09 UTC, stevending1st commented on pages/activity/[name]/team/[tid]/index.tsx
> +        : undefined;
> this.currentUserInThisTeam = user?.id
>         && await this.store.getOne(user.id);

`user.id` 有可能是空字符串~

2022-10-14 14:27 UTC, stevending1st commented on models/Team.ts
> +    this.changeOne({ status }, userId, true);
这个应该放到函数内判断，如果后面有状态增加方便判断。

2022-10-14 15:01 UTC, stevending1st commented on pages/activity/[name]/index.tsx
> +                  </Row>
![image](https://user-images.githubusercontent.com/23376142/195878719-9c702859-a625-4e6d-a5b1-e8fa67966c99.png)


![image](https://user-images.githubusercontent.com/23376142/195878837-e971dab2-99cc-4f1d-83ef-01d19f3b2358.png)

我还是觉得窄的好看~

2022-10-14 15:25 UTC, stevending1st commented on components/Team/TeamAdministratorTable.tsx
> +                      <td key={idx + userId}>
这是列~

2022-10-14 15:54 UTC, stevending1st commented on components/Team/TeamManageFrame.tsx
> +      this.isLoading = false;
```ts
  store = {} as TeamMemberModel;

  async componentDidMount() {
    const { name, tid } = this.props,
      { user } = sessionStore;
    this.store = activityStore.teamOf(name).memberOf(tid);

    try {
      const currentUserInThisTeam = user?.id && (await this.store.getOne(user.id));
      this.teamMemberRole = currentUserInThisTeam ? currentUserInThisTeam.role : '';
    } catch (error: any) {
      const { status } = error as ErrorBaseData;
      if (status !== 404) {
        this.teamMemberRole = '';
      }
    }
  }
```

我把核心修改代码贴到这里，有闪现，效果并不好，你自己试试吧。

2022-10-14 17:14 UTC, stevending1st commented on pages/activity/[name]/team/[tid]/manage/participant.tsx
> +  store = activityStore.teamOf(this.props.activity).memberOf(this.props.teamId);
没看懂~

2022-10-14 17:21 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/manage/participant.tsx
> +  store = activityStore.teamOf(this.props.activity).memberOf(this.props.teamId);
就是这个工具函数自动向 `props` 注入一个 `route` 对象，其属性都来自于 `req` 对象：

https://github.com/kaiyuanshe/OpenHackathon-Web/blob/main/pages/api/core.ts#L85-L90

2022-10-14 20:31 UTC, TechQuery requested changes

2022-10-14 20:31 UTC, TechQuery commented on models/Team.ts
> +}
```suggestion
export type TeamMemberFilter =
    Filter<TeamMember> & Partial<Pick<TeamMember, 'role' | 'status'>>;
```

2022-10-14 20:31 UTC, TechQuery commented on models/Team.ts
> +  role?: 'admin' | 'member';
```suggestion
export interface JoinTeamReqBody extends Pick<TeamMember, 'role'> {
```

2022-10-14 20:31 UTC, TechQuery commented on models/Team.ts
> +    return this.client.delete(`${this.baseURI}`);
```suggestion
    return this.client.delete(this.baseURI);
```

2022-10-14 20:31 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/index.tsx
> +      ],
由较复杂的条件或字面量数据合成的变量，最好声明为类的 getter 属性，`render()` 中直接取用，让代码更清晰。

2022-10-14 20:31 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/index.tsx
> +        </Modal>
模态框也建议放在独立的类方法中

2022-10-15 13:16 UTC, TechQuery requested changes

2022-10-15 13:16 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/index.tsx
> +    const { currentRoute, isShowJoinReqModal, handleJoinTeam } = this;
```suggestion
  @computed
  get isShowJoinTeamBtn() {
      const now = Date.now(),
          { eventStartedAt, eventEndedAt } = this.props.activity,
          { currentEnrollment, currentTeam } = activityStore;

      return now > +new Date(eventStartedAt) &&
        now < +new Date(eventEndedAt) &&
        currentEnrollment?.sessionOne?.status === 'approved' &&
        !currentTeam?.sessionOne;
  }

  @computed
  get isShowLeaveTeamBtn() {
      return activityStore.currentTeam?.sessionOne?.id === this.props.team.id
  }

  render() {
    const hackathonDisplayName = this.props.activity.displayName,
      {
        id,
        hackathonName,
        displayName,
        description,
        creator: { photo },
      } = this.props.team,
      { teamMemberList, teamWorkList } = this.props,
      {
        currentRoute,
        isShowJoinReqModal,
        handleJoinTeam,
        isShowJoinTeamBtn,
        isShowLeaveTeamBtn,
      } = this;
```

2022-10-15 14:52 UTC, TechQuery approved these changes

2022-10-15 14:52 UTC, TechQuery commented on pages/activity/[name]/team/[tid]/index.tsx
> +  @computed
```suggestion
```
getter 内没有可观察数据时无需 `@computed`

2022-10-15 14:55 UTC, merged