[feature] notice list
kaiyuanshe/OpenHackathon-Web pull request #116
Opened 2022-10-06 15:35 UTC by scluojie

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #109

2022-10-06 18:11 UTC, TechQuery requested changes

2022-10-06 18:11 UTC, TechQuery commented on models/Notice.ts
> +    baseURI = 'hackathon/foo/announcements';
路由需要替换不同活动的 `name`，参考：
https://github.com/kaiyuanshe/OpenHackathon-Web/blob/ba01208baeb0d0fdc2a4c90c2f97084ef7a2d59f/models/Team.ts#L73-L76

2022-10-06 18:11 UTC, TechQuery commented on models/Notice.ts
> +export default new NoticeModel();
因为公告是关联活动的，所以没法独立初始化，参考：
https://github.com/kaiyuanshe/OpenHackathon-Web/blob/ba01208baeb0d0fdc2a4c90c2f97084ef7a2d59f/models/Activity.ts#L65-L84

2022-10-06 18:11 UTC, TechQuery commented on pages/notice/index.tsx
> +import noticeStore from '../../models/Notice';
```suggestion
import { InferGetServerSidePropsType } from 'next';
import Table from 'react-bootstrap/Table';

import noticeStore from '../../models/Notice';
```

2022-10-06 18:11 UTC, TechQuery commented on pages/notice/index.tsx
> +}
该功能是公告管理，无需服务端渲染，且需放在
https://github.com/kaiyuanshe/OpenHackathon-Web/tree/main/pages/activity/%5Bname%5D/manage

2022-10-06 18:11 UTC, TechQuery commented on pages/notice/index.tsx
> +        </Table>
## 参考

- 列表组件：https://github.com/kaiyuanshe/OpenHackathon-Web/blob/main/components/EnrollmentList.tsx
- 管理页面：https://github.com/kaiyuanshe/OpenHackathon-Web/blob/main/pages/activity/%5Bname%5D/manage/participant.tsx

2022-10-12 22:34 UTC, TechQuery requested changes
1. 上次 review 的一些问题没改
2. `pages/notice/index.tsx` 文件删掉

2022-10-12 22:34 UTC, TechQuery commented on pages/activity/[name]/manage/message.tsx
> +  }
合并主分支后，路由取参数的方式会简化，参考：
https://github.com/kaiyuanshe/OpenHackathon-Web/blob/b442bd301fbf796d77f777d3c11f600c5e019768/pages/activity/%5Bname%5D/manage/participant/index.tsx#L13-L19

2022-10-12 22:34 UTC, TechQuery commented on pages/activity/[name]/manage/message.tsx
> +            activity={activity}/>
看起来你的电脑执行自动格式化失败，请安装编辑器插件手动格式化：
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2022-10-12 22:34 UTC, TechQuery commented on pages/activity/[name]/manage/message.tsx
> +    extensions?: Message;
没有用到的类成员删掉

2022-10-12 22:34 UTC, TechQuery commented on components/MessageList.tsx
> +    content: string;
这些属性是列表每一项的字段，并非外面传给整个组件的参数，应删掉。

2022-10-12 22:34 UTC, TechQuery commented on components/MessageList.tsx
> +    content: string;
这些属性是列表每一项的字段，并非外面传给整个组件的参数，应删掉。

2022-10-12 22:34 UTC, TechQuery commented on components/MessageList.tsx
> +    content: string;
这些属性是列表每一项的字段，并非外面传给整个组件的参数，应删掉。

2022-10-12 22:34 UTC, TechQuery commented on components/MessageList.tsx
> +  static Layout = ({ value = [], hackathonName,title,content }: MessageListProps) => (
```suggestion
  static Layout = ({ value = [] }: MessageListProps) => (
```

2022-10-12 22:34 UTC, TechQuery commented on models/Message.ts
> +  id: string;
```suggestion
export interface Message extends Base {
  hackathonName: string;
```
基类已有属性无需再写

2022-10-12 22:34 UTC, TechQuery commented on models/Message.ts
> +  indexKey = "id" as const;
```suggestion
```
该属性的基类默认值为 `id`，无需重复声明

2022-10-12 22:34 UTC, TechQuery commented on models/Message.ts
> +  sessionOne?: Message;
没有与获取当前登录用户相关的专有数据的方法，此属性无用，删掉。

2022-10-16 11:49 UTC, scluojie commented on components/MessageList.tsx
> +  static Layout = ({ value = [], hackathonName,title,content }: MessageListProps) => (
ok

2022-10-16 20:33 UTC, TechQuery requested changes

2022-10-16 20:33 UTC, TechQuery commented on pages/activity/[name]/manage/message.tsx
> +      <ActivityManageFrame name={activity} path={basePath} title="公告管理">
`<ActivityManageFrame path={} />` 需要的并非后端接口的路径，而是前端页面的路径，参考：

https://github.com/kaiyuanshe/OpenHackathon-Web/blob/ac36a02b76fa18d873392fc432a63dcf0ebc3580/pages/activity/%5Bname%5D/manage/award.tsx#L128-L132

2022-10-19 16:24 UTC, TechQuery requested changes

2022-10-19 16:24 UTC, TechQuery commented on components/Message/ActivityMessageModal.tsx
> +              defaultValue={this.props.store.currentOne.content}
上方解构，如：
```ts
const { store } = this.props;
const { content } = store.currentOne;
```

2022-10-19 16:24 UTC, TechQuery commented on components/Message/MessageEditor.tsx
> +export const MessageEditor: FC<MessageEditorProps> = ({ message,onSubmit }) => (
```suggestion
export const MessageEditor: FC<MessageEditorProps> = ({ message, onSubmit }) => (
```

2022-10-19 16:24 UTC, TechQuery commented on components/Message/MessageEditor.tsx
> +    </Row>
```suggestion
    <footer className="text-center">
      <Button variant="primary" type="submit">提交</Button>
    </footer>
```

2022-10-19 16:24 UTC, TechQuery commented on pages/activity/[name]/manage/message.tsx
> +  show = false;
属性放上面，方法放下面

2022-10-19 16:24 UTC, TechQuery commented on pages/activity/[name]/manage/message.tsx
> +          }}
```suggestion
          onEdit={() => (this.show = true)}
```

2022-10-19 16:24 UTC, TechQuery commented on components/Message/MessageList.tsx
> +                    : value.map(({ id }) => String(id)),
```suggestion
                    : value.map(({ id }) => id + ''),
```
（下同）

2022-10-23 19:43 UTC, TechQuery approved these changes

2022-10-23 19:43 UTC, merged