[add]: topUserList
kaiyuanshe/OpenHackathon-Web pull request #117
Opened 2022-10-09 13:33 UTC by Five-great

Checklist（清单）:

- [x] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #115

2022-10-10 05:12 UTC, Five-great commented
浏览链接 https://openhackathonweb.vercel.app/

2022-10-12 23:52 UTC, TechQuery requested changes

2022-10-12 23:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +              <i></i>
```suggestion
              <i />
```
下同

2022-10-12 23:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +                    </p>
```suggestion
                    <address>
                      {user?.email && (
                        <a href={'mailto:' + user.email}>
                          <FontAwesomeIcon icon={faEnvelope} />
                        </a>
                      )}
                      {parseFn(user?.oAuth)?.html_url && (
                        <a
                          className="ms-2"
                          rel="noreferrer"
                          target="_blank"
                          href={parseFn(user?.oAuth)?.html_url}
                        >
                          <FontAwesomeIcon icon={faGithub} />
                        </a>
                      )}
                    </address>
```
1. 标签语义
2. 非页面链接浏览器会自动弹框，不会刷新当前页
3. 间距用 CSS 工具类：https://getbootstrap.com/docs/5.2/utilities/spacing/
4. 可以抽个函数组件给下面复用

2022-10-12 23:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +                    </Badge>
纯样式用工具类：https://getbootstrap.com/docs/5.2/utilities/text/#font-weight-and-italics

2022-10-12 23:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +                  </td>
```suggestion
                  <td className={`position-relative ${styles.usernameBox}`}>
                      <div className={styles.imgBox}>
                        <Image
                          className={styles.topUserAvatar}
                          src={user?.photo || parseFn(user?.oAuth)?.avatar_url}
                          alt={
                            user?.nickname ||
                            user?.name ||
                            user?.username ||
                            '神秘黑客'
                          }
                        />
                      </div>
                      <a href={user?.profile} className="stretched-link">
                        style={{
                          color: `rgb(248, ${(rank - 2) * 15}, ${(rank - 2) * 35})`
                        }}
                      >
                        {user?.nickname ||
                          user?.name ||
                          user?.username ||
                          '神秘黑客'}
                    </a>
                  </td>
```
1. `<a />` 不能套在块级元素外，需要扩大点击区域，请用工具类：https://getbootstrap.com/docs/5.2/helpers/stretched-link/
2. 多段字符串连接用**模板字符串语法**更清晰

2022-10-12 23:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +                  </td>
```suggestion
                  <td>{score}</td>
```
如无必要，减少嵌套

2022-10-12 23:52 UTC, TechQuery commented on models/User.ts
> +  updatedAt: null;
时间戳怎么可能是 `null`？

2022-10-12 23:52 UTC, TechQuery commented on models/User.ts
> +  // }
删掉无用代码

2022-10-12 23:52 UTC, TechQuery commented on models/User.ts
> +    return value;
```suggestion
    return body!.value;
```

2022-10-12 23:52 UTC, TechQuery commented on pages/index.tsx
> +        marginTop: '-3rem!important',
React 内联样式无法使用 `!important`

2022-10-12 23:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +  static Layout = ({ value = [] }: TopUserListProps) => (
```suggestion
export const TopUserList = ({ value = [] }: TopUserListProps) => (
```
没继承 `ScrollList` 抽象组件（无上拉加载更多）就没必要这么写，完全依赖服务端渲染的直接写成函数组件即可。

2022-10-12 23:52 UTC, TechQuery commented on styles/TopUserList.module.less
> +      min-height: 100%;
都有工具类：https://getbootstrap.com/docs/5.2/utilities/api/

2022-10-12 23:52 UTC, TechQuery commented on styles/TopUserList.module.less
> +      transition: 0.6s;
```suggestion
      transition: 0.6s;
```
厂商前缀现代编译器都会处理（下同）

2022-10-12 23:52 UTC, TechQuery commented on styles/TopUserList.module.less
> +      color: transparent;
能用工具类替代的就改一下
https://getbootstrap.com/docs/5.2/utilities/api/

2022-10-12 23:52 UTC, TechQuery commented on styles/TopUserList.module.less
> +      text-align: center;
https://getbootstrap.com/docs/5.2/utilities/api/

2022-10-12 23:52 UTC, TechQuery commented on styles/TopUserList.module.less
> +      }
```suggestion
      &:hover .imgBox {
          animation-play-state: paused;
      }
```

2022-10-12 23:52 UTC, TechQuery commented on styles/TopUserList.module.less
> +        border-radius: 2rem;
https://getbootstrap.com/docs/5.2/utilities/api/

2022-10-12 23:52 UTC, TechQuery commented on styles/TopUserList.module.less
> +      box-shadow: 0 0 0.5rem 0 #c6c6c6;
https://getbootstrap.com/docs/5.2/utilities/api/

2022-10-12 23:52 UTC, TechQuery commented on styles/TopUserList.module.less
> +      text-overflow: ellipsis;
https://getbootstrap.com/docs/5.2/utilities/api/

2022-10-12 23:52 UTC, TechQuery commented on styles/TopUserList.module.less
> +        }
```suggestion
        &:hover .imgBox > img {
            transform: scale(1.2);
        }
```

2022-10-12 23:52 UTC, TechQuery commented on styles/TopUserList.module.less
> +          vertical-align: middle;
https://getbootstrap.com/docs/5.2/utilities/api/

2022-10-14 04:14 UTC, Five-great commented on models/User.ts
> +  updatedAt: null;
当时不确定 项目给时间弄的撒我看到很多填null 我就先填着 后面问来着

2022-10-14 04:15 UTC, Five-great commented on models/User.ts
> +  // }
这个我也是打算问来着 想着线上调试就没删

2022-10-14 04:18 UTC, Five-great commented on styles/TopUserList.module.less
> +      min-height: 100%;
之前开发习惯自己写 了解 bootstrap 不够 学习了 感谢水歌，👍

2022-10-16 20:52 UTC, TechQuery requested changes

2022-10-16 20:52 UTC, TechQuery commented on components/User/TopUserAddress.tsx
> +}
```suggestion
export type TopUserAddressProps = Partial<Record<'email' | 'github', string>>;
```

2022-10-16 20:52 UTC, TechQuery commented on components/User/TopUserAddress.tsx
> +  </>
```suggestion
    <address className="mb-0">
      {email && (
        <a rel="noreferrer" target="_blank" href={'mailto:' + email}>
          <FontAwesomeIcon icon={faEnvelope} />
        </a>
      )}
      {github && (
        <a rel="noreferrer" className="ms-2" target="_blank" href={github}>
          <FontAwesomeIcon icon={faGithub} />
        </a>
      )}
    </address>
```
（自查其它文件）

2022-10-16 20:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +              <div>
感觉这一层是多余的

2022-10-16 20:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +            <li key={userId} className="col">
```suggestion
        <Row
          as="ul"
          className={`list-unstyled mt-2 ps-0 pt-2 g-0 align-items-end text-center ${styles.topUserUl}`}
        >
          {value.slice(0, 3).map(({ userId, score, user }) => (
            <Col as="li" key={userId}>
```

2022-10-16 20:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +                  </p>
此处语义非“段落”，感觉是一级标题

2022-10-16 20:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +                    {rank < 9 ? '0' : ''}
```suggestion
                    {rank < 9 && 0}
```

2022-10-16 20:52 UTC, TechQuery commented on components/User/TopUserList.tsx
> +                      className={'w-100'}
```suggestion
                      className="w-100"
```

2022-10-17 02:20 UTC, Five-great commented on components/User/TopUserList.tsx
> +                  </p>
感觉一级标题也不太合适 只是一个人昵称 我用span吧

2022-10-17 02:26 UTC, closed without merging