I18n
kaiyuanshe/OpenHackathon-Web pull request #119
Opened 2022-10-12 00:49 UTC by scarqin

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2022-10-12 00:50 UTC, scarqin commented
duplicate https://github.com/kaiyuanshe/OpenHackathon-Web/issues/19

2022-10-12 01:44 UTC, scarqin commented
@TechQuery 技术栈你看看有没问题，没问题剩下的就是格式化和翻译了

2022-10-12 22:40 UTC, TechQuery requested changes

2022-10-12 22:40 UTC, TechQuery commented on pages/_app.tsx
> +import { useTranslation } from 'react-i18next';
第三方库放上面

2022-10-12 22:40 UTC, TechQuery commented on utils/i18n.ts
> +export default i18n;
```suggestion
```

2022-10-16 17:52 UTC, scarqin commented
@TechQuery 服务端怎么缓存系统设置的语言数据？

2022-10-16 21:22 UTC, TechQuery approved these changes

2022-10-16 21:24 UTC, TechQuery requested changes

2022-10-16 21:24 UTC, TechQuery commented on components/layout/MainNavigation.tsx
> +  return (
省略 `{ return }`

2022-10-16 21:24 UTC, TechQuery commented on components/User/UserBar.tsx
> +  };
```suggestion
  const changeLanguage = (language: string) =>
    i18n.changeLanguage(localStorage.language = language);
```

2022-10-16 21:24 UTC, TechQuery commented on components/User/UserBar.tsx
> +        </Dropdown.Menu>
少了正体中文选项

2022-10-17 01:03 UTC, scarqin commented on components/User/UserBar.tsx
> +        </Dropdown.Menu>
@TechQuery 需求里面没有，可以先不增加额外翻译成本。

2022-10-17 13:34 UTC, TechQuery commented on components/User/UserBar.tsx
> +        </Dropdown.Menu>
> @TechQuery 需求里面没有，可以先不增加额外翻译成本。

但你移过来的我的旧代码都翻译了，他们没需求不去点就是了，即便翻译，正体、简体转换也可以先字字互译。

2022-10-25 14:33 UTC, TechQuery commented on components/layout/MainNavigation.tsx
>  export const MainNavigation = () => (
不要把空行删掉

2022-10-25 14:35 UTC, TechQuery commented on utils/i18n.ts
>  i18n.use(initReactI18next).init({
导入和正文间留空行

2022-10-27 17:39 UTC, TechQuery requested changes

2022-10-27 17:39 UTC, TechQuery commented on components/Team/TeamAdministratorTable.tsx
>    '最后登录时间',
这里咋没翻译？

2022-10-27 17:39 UTC, TechQuery commented on components/TeamEditor.tsx
> +        {t('name')}（必填）
还有没翻译的

2022-10-27 17:39 UTC, TechQuery commented on components/User/StaffList.tsx
>    '最后登录时间',
漏掉+1

2022-10-27 17:39 UTC, TechQuery commented on locales/en-US.json
> +  "powerful_driver": "idea2app 脚手架强力驱动",
这是？

2022-10-27 17:39 UTC, TechQuery commented on models/Question.ts
> +      t('others'),
该模块是临时预置了一些问题，kaiyuanshe/open-hackathon-api#337 完成后会完全依赖后端数据，此处会删除。

2022-11-10 05:24 UTC, stevending1st commented on components/EnrollmentList.tsx
>            <th>联系地址</th>
这个不翻译还是没有弄好~

2022-11-10 18:36 UTC, TechQuery approved these changes

2022-11-12 14:19 UTC, scarqin commented on locales/en-US.json
> +  "powerful_driver": "idea2app 脚手架强力驱动",
首页的提示

2022-11-12 14:20 UTC, scarqin commented on models/Question.ts
> +      t('others'),
好，那到时候删除后你们再操作吧

2022-11-12 14:39 UTC, scarqin commented
@TechQuery 合并了

2022-11-12 16:31 UTC, TechQuery approved these changes

2022-11-12 16:32 UTC, merged