[add] activity dynmaic list
kaiyuanshe/OpenHackathon-Web pull request #134
Opened 2022-10-27 04:26 UTC by wangrunlin

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #120

2022-10-27 04:31 UTC, wangrunlin commented
- 数据无法成功渲染

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/64216877/198191846-968bd6ff-639e-44ef-a8bf-eb4003b2a974.png">

2022-10-27 17:07 UTC, TechQuery requested changes

2022-10-27 17:07 UTC, TechQuery commented on models/Log.ts
> +  }
```suggestion
  client = sessionStore.client;

  constructor(baseURI: string) {
    super();
    this.baseURI = `${baseURI}/activityLogs`;
  }
```

2022-10-27 17:07 UTC, TechQuery commented on components/Activity/ActivityLogList.tsx
> +    </div>
```suggestion
    <ul>
      {value.map(item => {
        <li key={item.id}>
          <span>{item.activityLogType}</span>
          <span>{item.message}</span>
          <span>{item.messageFormat}</span>
        </li>;
      })}
    </ul>
```
注意 **HTML 标签语义**

2022-10-27 17:14 UTC, TechQuery commented
> * 数据无法成功渲染
> 
> <img alt="image" width="1920" src="https://user-images.githubusercontent.com/64216877/198191846-968bd6ff-639e-44ef-a8bf-eb4003b2a974.png">

这可能与上游组件某些情况下监听不到**滚动触底**有关，可能是监听时的根元素需要按需设置：
1. https://github.com/idea2app/Idea-React/blob/e51f9f64d9e5ddf3b9eae4bf37f9f86a87ec4574/source/ScrollBoundary.tsx#L17-L19
2. https://developer.mozilla.org/zh-CN/docs/Web/API/IntersectionObserver#%E5%B1%9E%E6%80%A7

我抽空调试一下吧

2022-10-27 18:24 UTC, TechQuery requested changes

2022-10-27 18:24 UTC, TechQuery commented on components/Activity/ActivityLogList.tsx
> +      })}
```suggestion
      {value.map(item => (
        <li key={item.id}>
          <span>{item.activityLogType}</span>
          <span>{item.message}</span>
          <span>{item.messageFormat}</span>
        </li>
      ))}
```
bug 在此

2022-10-27 18:28 UTC, TechQuery commented
> * 数据无法成功渲染
> 
> <img alt="image" width="1920" src="https://user-images.githubusercontent.com/64216877/198191846-968bd6ff-639e-44ef-a8bf-eb4003b2a974.png">

破案了：https://github.com/kaiyuanshe/OpenHackathon-Web/pull/134#discussion_r1007220650

2022-10-27 18:30 UTC, wangrunlin commented on components/Activity/ActivityLogList.tsx
> +      })}
太致命的错误了，学习了

2022-10-28 16:58 UTC, TechQuery requested changes

2022-10-28 16:58 UTC, TechQuery commented on components/Activity/ActivityLogList.tsx
> +          <Badge>{item.activityLogType}</Badge>
```suggestion
      {value.map(({ id, message, activityLogType }) => (
        <ListGroup.Item
          key={id}
          as="li"
          className="d-flex justify-content-between"
        >
          <div className="ms-2 me-auto">{message}</div>
          <Badge>{activityLogType}</Badge>
```

2022-10-28 16:58 UTC, TechQuery commented on components/Organization/OrganizationList.tsx
> +        <Row key={item.id} style={{ padding: '.5rem' }}>
```suggestion
        <Row key={item.id} className="p-2">
```
https://getbootstrap.com/docs/5.2/utilities/spacing/#margin-and-padding

2022-10-28 16:59 UTC, TechQuery approved these changes

2022-10-28 16:59 UTC, merged