add admin frame
kaiyuanshe/OpenHackathon-Web pull request #135
Opened 2022-10-28 13:11 UTC by stevending1st

Checklist（清单）:
add admin frame

- [x] Labels
- [ ] Assignees
- [x] Reviewers

Closes #XXXXX

2022-10-29 05:05 UTC, TechQuery requested changes

2022-10-29 05:05 UTC, TechQuery commented on components/Admin/AdminFrame.tsx
> +                <Nav.Link className="text-nowrap">
- 可以不用 `<Link />`
- `<Nav.Link />` 激活状态也处理一下

参考活动管理员布局最新代码

2022-10-29 05:05 UTC, TechQuery commented on pages/admin/index.tsx
> +  <AdminFrame title="活动管理" path="/">
标题有误

2022-11-26 13:34 UTC, stevending1st commented on components/Admin/AdminFrame.tsx
> +                <Nav.Link className="text-nowrap">
> * `<Nav.Link />` 激活状态也处理一下

`location` 未定义，类组件不知道怎么搞，其他的我对比一下，没有什么区别，不知道为啥   **活动管理员布局** 可以。

2022-11-26 13:49 UTC, TechQuery commented on components/Admin/AdminFrame.tsx
> +                <Nav.Link className="text-nowrap">
因为类组件有部分是客户端渲染，函数组件一定会走一道服务端渲染，应用：
```js
globalThis.location?.pathname
```

2022-11-26 16:48 UTC, stevending1st commented
@TechQuery  [authorized](https://github.com/kaiyuanshe/OpenHackathon-Web/pull/135/files#diff-dcb0a154b21c405f70d266264ff9cc1c82aee0a4ab80f5c4a60db402050bc125R61-R64) 是同步的，无法通过异步请求成功与否判断是否有权限。

2022-11-26 17:53 UTC, TechQuery requested changes

2022-11-26 17:53 UTC, TechQuery commented on package.json
> +    "jsdom": "^20.0.0",
设为开发依赖

2022-11-26 17:53 UTC, TechQuery commented on package.json
> +    "@editorjs/paragraph": "^2.8.0",
一些打包期间提示安装的可选依赖，当做开发依赖即可。

2022-11-26 17:53 UTC, TechQuery commented on pages/admin/index.tsx
> +  <PlatformAdminFrame title="活动管理" path="/">
i18n

2022-11-26 17:53 UTC, TechQuery commented on components/PlatformAdmin/PlatformAdminFrame.tsx
> +  }
可用查**平台管理员列表接口**是否报错，来临时设置这个值

2022-11-27 03:55 UTC, stevending1st commented
> @TechQuery [authorized](https://github.com/kaiyuanshe/OpenHackathon-Web/pull/135/files#diff-dcb0a154b21c405f70d266264ff9cc1c82aee0a4ab80f5c4a60db402050bc125R61-R64) 是同步的，无法通过异步请求成功与否判断是否有权限。

已解决

2022-11-27 11:08 UTC, TechQuery approved these changes

2022-11-27 11:08 UTC, TechQuery commented on components/PlatformAdmin/PlatformAdminFrame.tsx
> +  }
放到状态管理那边

https://github.com/kaiyuanshe/OpenHackathon-Web/blob/sd/admin-frame/models/PlatformAdmin.tsL16-L30

2022-11-27 11:08 UTC, TechQuery commented on components/PlatformAdmin/PlatformAdminFrame.tsx
> +  }
不做任何处理直接取值，这样没必要。

2022-11-27 11:08 UTC, TechQuery commented on locales/zh-Hant-TW.json
> +  "admin_management": "**wait for translate"
先用繁体输入模式写一下吧

2022-11-27 11:08 UTC, TechQuery commented on models/PlatformAdmin.ts
> +  userId: string;
可以用 `Record` 泛型简化一下。

2022-11-27 11:08 UTC, TechQuery commented on models/PlatformAdmin.ts
> +export interface PlatformAdminFilter extends Filter<PlatformAdmin> {}
没有额外字段可以直接用 `type`。

2022-11-27 18:18 UTC, TechQuery requested changes

2022-11-27 18:18 UTC, TechQuery commented on components/PlatformAdmin/PlatformAdminFrame.tsx
>      }
这块逻辑都移过去

2022-11-28 12:01 UTC, TechQuery approved these changes

2022-11-28 12:03 UTC, merged