发布新活动
kaiyuanshe/OpenHackathon-Web pull request #16
Opened 2020-11-24 22:07 UTC by gakki88

close #12

2020-11-25 11:32 UTC, TechQuery requested changes

2020-11-25 11:32 UTC, TechQuery commented on src/page/Activity/CreateActivity.tsx
> +        } = formToJSON(target as HTMLFormElement);
`<form />` 中输入框的 **`name` 属性值**与**后端接口字段名**一一对应的话，此处可用直接写 ——

```TypeScript
const data = formToJSON<Partial<Activity>>(event.target as HTMLFormElement);

await activity.createActivity({
    ...data,
    // 更多字段
});
```
无需处处用 `as` 断言了。

2020-11-25 11:32 UTC, TechQuery commented on src/page/Activity/CreateActivity.tsx
> +            description: JSON.stringify(this.description.getContents()),
根据 quilljs/quill#903 可知，获取**编辑器的 HTML 结果**应写为：
```JavaScript
this.description.root.innerHTML
```

2020-11-26 20:06 UTC, TechQuery requested changes

2020-11-26 20:06 UTC, TechQuery commented on src/model/Activity.ts
> +    description: HTMLFormElement;
来自后端的数据不可能是个 `<form />` 元素

2020-11-26 20:06 UTC, TechQuery commented on src/page/Activity/ManagerOverview.tsx
> +        console.log(registrations);
调试用代码不要提交上来

2020-11-26 20:09 UTC, TechQuery commented on src/page/Activity/CreateActivity.tsx
> +            description: JSON.stringify(this.description.getContents()),
`description` 字段的值还是要用上述方法手动获取

2020-11-26 20:11 UTC, TechQuery requested changes

2020-11-26 20:11 UTC, TechQuery commented on src/page/Activity/CreateActivity.tsx
> +                    name="description"
`<div />` 不是 **HTML 表单元素**，没有 `name` 属性

2020-11-26 22:26 UTC, gakki88 commented on src/model/User.ts
> +    remark: string;
只在这里加了`remark: string;`

2020-11-27 07:40 UTC, TechQuery requested changes

2020-11-27 07:40 UTC, TechQuery commented on src/page/Activity/CreateActivity.tsx
> +    description;
`@attribute` 装饰器是 WebCell 用于把 **DOM 元素的 property** 同步为 **HTML 标签的 attribute** 的，而此处的 `description` 只是用来存 **Quill 编辑器对象实例**的，一般这样的**非数据对象**会做如下声明：

```TypeScript
import { component, mixin } from 'web-cell';
import Quill from 'quill';

@component({
    tagName: 'create-activity',
    renderTarget: 'children'
})
export class CreateActivity extends mixin() {
    private description: Quill;
}
```

2020-11-27 16:54 UTC, TechQuery approved these changes

2020-11-27 16:56 UTC, merged