[polish] form validation
kaiyuanshe/OpenHackathon-Web pull request #162
Opened 2023-03-05 14:37 UTC by Soecka

Checklist（清单）:

- [X] Labels
- [ ] Assignees
- [X] Reviewers

- Closes #161

2023-03-05 16:46 UTC, TechQuery requested changes

2023-03-05 16:46 UTC, TechQuery commented on components/ActivityEditor.tsx
> +              required
不是所有的字段都是必选

2023-03-05 16:46 UTC, TechQuery commented on components/ActivityEditor.tsx
> +              type="text"
```suggestion
```
默认值可省略

2023-03-06 04:12 UTC, Soecka commented on components/ActivityEditor.tsx
> +              type="text"
点解？
默认值是 string 所以可以省略` type=‘text’` ？

2023-03-06 06:02 UTC, TechQuery approved these changes

2023-03-06 06:03 UTC, TechQuery commented on components/ActivityEditor.tsx
> +              type="text"
`<input />` 默认值就是 `type="text"`

2023-03-06 06:05 UTC, merged