[feature] add date time comparison logic
kaiyuanshe/OpenHackathon-Web pull request #168
Opened 2023-05-19 13:54 UTC by PapayaHUANG

- [x] Labels
- [x] Assignees
- [x] Reviewers

Closes  #164

2023-05-19 15:08 UTC, TechQuery commented on components/ActivityEditor.tsx
> -
此处更改的原因是？

2023-05-19 15:18 UTC, TechQuery commented on components/DateTimeInput.tsx
> +      dateTimeInputStore.end,
你这个 store 完全没用于数据响应，而且全局共享一个实例，组件在复用时数据会串的。

你只是控制内部 invalid 状态的话，完全可以写成一个类组件，用 `@observable` 内部控制状态，不需要去外面绕一圈。

2023-05-19 15:21 UTC, TechQuery commented on components/DateTimeInput.tsx
> +  };
```suggestion
  const isValidDateTime = (startAt?: string, endAt?: string) =>
      +new Date(startAt) <= +new Date(endAt);
```
非法日期转为数值是 `NaN`，与任何数比较都是 `false`。

2023-05-19 15:22 UTC, TechQuery commented on components/DateTimeInput.tsx
> +    const { name, value } = event.target;
```suggestion
  const handleInputChange = ({ currentTarget: { name, value } }: ChangeEvent<HTMLInputElement>) => {
```

2023-05-20 16:36 UTC, PapayaHUANG commented on components/DateTimeInput.tsx
> +  };
我还是写的isInvalid
因为start和end的初始值是`''`，转换一下就会变成`NaN`，那isValid就是`false`，变成isInvalid就是`true`，也就是在没有输入任何日期的情况下，就会报错。
所以我还是写的isInvalid的逻辑

2023-05-20 16:52 UTC, TechQuery requested changes

2023-05-20 16:52 UTC, TechQuery commented on components/DateTimeInput.tsx
> +import { ChangeEvent } from 'react';
```suggestion
import { ChangeEvent, PureComponent } from 'react';
```

2023-05-20 16:52 UTC, TechQuery commented on components/DateTimeInput.tsx
> +              isInvalid={this.isInvalid}
```suggestion
    const { id, label, name, required, startAt, endAt } = this.props,
        { isInvalid } = this;

    return (
      <Form.Group as={Row} className="mb-3" controlId={id}>
        <Form.Label column sm={2}>
          {label}
        </Form.Label>
        <Col sm={10}>
          <InputGroup className="mb-3">
            <InputGroup.Text>{t('time_range')}</InputGroup.Text>
            <Form.Control
              name={`${name}StartedAt`}
              type="datetime-local"
              defaultValue={
                startAt && formatDate(startAt, 'YYYY-MM-DDTHH:mm:ss')
              }
              {...{ required, isInvalid }}
              onChange={this.handleInputChange}
            />
            <Form.Control
              name={`${name}EndedAt`}
              type="datetime-local"
              defaultValue={endAt && formatDate(endAt, 'YYYY-MM-DDTHH:mm:ss')}
              {...{ required, isInvalid }}
```

2023-05-20 18:42 UTC, TechQuery approved these changes

2023-05-20 18:43 UTC, merged