feat: Sign up for custom fields
kaiyuanshe/OpenHackathon-Web pull request #173
Opened 2023-06-01 13:09 UTC by Darrenjoe

Checklist（清单）:

- [ ] 报名时校验问卷是否存在
- [ ] 问卷页面渲染

Closes #95

2023-06-06 14:32 UTC, TechQuery commented on models/Activity.ts
> +}
```suggestion
import { Base } from './Base';

export interface Questionnaire extends Base {
  extensions: Extensions[];
  hackathonName: string;
}
```

2023-06-06 14:33 UTC, TechQuery commented on models/Activity.ts
> +    return res;
```suggestion
  async getQuestionnaire(activity = this.currentOne.name) {
    const {body} = await this.client.get<Questionnaire>(
      `${this.baseURI}/${activity}/questionnaire`,
    );
    return body;
```
（下同）

2023-06-06 14:35 UTC, TechQuery commented on models/Activity.ts
> +    return this.client.put(`${this.baseURI}/${name}/questionnaire`, {
```suggestion
  createQuestionnaire(extensions: Extensions[], activity = this.currentOne.name) {
    return this.client.put(`${this.baseURI}/${activity}/questionnaire`, {
```

2023-06-08 14:39 UTC, TechQuery requested changes

2023-06-08 14:39 UTC, TechQuery commented on models/Activity.ts
> +    }
```suggestion
      const { body } = await this.client.get<Questionnaire>(
        `${this.baseURI}/${activity}/questionnaire`,
      );
      const questionnaire = body!.extensions.map(
        v => JSON.parse(v.value) as Question,
      );
      return questionnaire;
```
尽量不要吞异常，让上层去 `catch`。

2023-06-08 14:39 UTC, TechQuery commented on pages/activity/[name]/index.tsx
> +        {isShowSignupBtn && this.props.questionnaire.length > 0 && (
这个数据移到 model 侧，在客户端渲染时调用、检测。如：
```ts
class ActivityModel {
    @observable
    questionnaire = [];

    async getQuestionnaire() {
        return this.questionnaire = [];
    }
}
```

2023-06-08 14:39 UTC, TechQuery commented on pages/activity/[name]/index.tsx
> +          <Button onClick={() => registerNow()} disabled={isDisableSignupBtn}>
```suggestion
        ) : (
          <Button onClick={registerNow} disabled={isDisableSignupBtn}>
```

2023-06-10 10:02 UTC, TechQuery requested changes

2023-06-10 10:02 UTC, TechQuery commented on pages/activity/[name]/index.tsx
> +        )}
```suggestion
        {isShowSignupBtn && (this.questionnaire[0] ? (
           <Button
             href={`/activity/${name}/register`}
             disabled={isDisableSignupBtn}
           >
             {t('register_now')}
           </Button>
         ) : (
          <Button onClick={registerNow} disabled={isDisableSignupBtn}>
            {t('register_now')}
          </Button>
        )}
```

2023-06-10 11:29 UTC, Darrenjoe commented on pages/activity/[name]/index.tsx
> +    console.log('questionnaire', this.questionnaire);
这里的activityStore.signOne方法只有报名功能，没有修改store的依赖，所以页面没有变化

2023-06-10 11:55 UTC, TechQuery requested changes

2023-06-10 11:55 UTC, TechQuery commented on models/Activity.ts
> +  @observable
```suggestion
  currentOrganization?: OrganizationModel;

  @observable
```

2023-06-10 11:55 UTC, TechQuery commented on pages/activity/[name]/index.tsx
> +    self.location.reload();
```suggestion
    const { name } = this.props.activity;

    await activityStore.signOne(name, []);

    self.alert(textJoin(t('hackathons'), name, t('registration_needs_review')));
    self.location.reload();
```
声明、逻辑、返回/提示三段论间空行。

2023-06-16 07:22 UTC, TechQuery requested changes

2023-06-16 07:22 UTC, TechQuery commented on components/Activity/QuestionnaireTable.tsx
> +  };
```suggestion
import { FC } from 'react';
import { observer } from 'mobx-react';

export const QuestionnaireTable: FC<QuestionnaireTableProps> = observer(({
  questionnaire,
  onDelete,
  onMove,
}) => {
  const typeMap = { text: t('text'), url: t('link') };
```

MobX i18n 需要 `observer()` 来更新

2023-06-16 07:22 UTC, TechQuery commented on components/Activity/QuestionnaireTable.tsx
> +                    ? multiple
```suggestion
                <td>{typeMap[type] || '--'}</td>
                <td>{options?.join(';') || '--'}</td>
                <td>
                  {options ? multiple
```

2023-06-16 07:22 UTC, TechQuery commented on components/Activity/QuestionnaireTable.tsx
> +                  )}
```suggestion
            ({ id, title, options, multiple, type, required }, index, { length }) => (
              <tr key={id}>
                <td>{index + 1}</td>
                <td>{id}</td>
                <td>{title}</td>
                <td>{type ? typeMap[type] : '--'}</td>
                <td>{options ? options?.join(';') : '--'}</td>
                <td>
                  {options && typeof multiple === 'boolean'
                    ? multiple
                      ? t('multiple')
                      : t('not_multiple')
                    : '--'}
                </td>
                <td>{required ? t('yes') : t('no')}</td>
                <td>
                  {!!index && (
                    <Button variant="link" onClick={() => onMove(id!, -1)}>
                      {t('move_up')}
                    </Button>
                  )}
                  {index !== length - 1 && (
                    <Button variant="link" onClick={() => onMove(id!, 1)}>
                      {t('move_down')}
                    </Button>
                  )}
```

2023-06-16 07:22 UTC, TechQuery commented on pages/activity/[name]/manage/questionnaire.tsx
> +export const getServerSideProps = withRoute<{ name: string }>();
```suggestion
const { t } = i18n;

export const getServerSideProps = withRoute<{ name: string }>();
```

2023-06-16 07:22 UTC, TechQuery commented on pages/activity/[name]/manage/questionnaire.tsx
> +    }
```suggestion
    if (!questionnaire[0]) return self.alert(t('please_add_question'));
```

2023-06-16 07:22 UTC, TechQuery commented on pages/activity/[name]/manage/questionnaire.tsx
> +    activityStore.editQuestionnaireStatus([]);
把删除清数组操作放在 `activityStore.deleteQuestionnaire()` 中

2023-06-16 07:22 UTC, TechQuery commented on pages/activity/[name]/manage/questionnaire.tsx
> +          </Col>
```suggestion
          <Col sm={12} className="p-2">
              <h5 className="mx-2">{t('preview_questionnaire')}</h5>
              <QuestionnairePreview questionnaire={questionnaire} />
          </Col>
```

2023-06-16 07:56 UTC, PapayaHUANG requested changes
英文翻译的修改，有一些具体的改动要看你的上下文，我指提了建议。
有问题的话，欢迎随时讨论。：）

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  edit_questionnaire: 'Questionnaire',
'Edit Questionnaire'

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  question_id_repeat: 'Question ID cannot be repeated',
'Please do not duplicate Question ID'
我不知道这里的context，但是重复这边用duplicate这个词

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  whether_multiple: 'Multiple choice or not',
'More than one answer or not'

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  multiple: 'Checkbox',
'Choose all that apply'
英语里面没有多项选择和单项选择的概念，multiple-choice question就是有多个选项的问题，所以既可以是单选题也可以是多选题。
所以这里的处理就是用短语表达可以选多个答案。

我不确定checkbox和radio这个概念对于非码农来说会对应成“多选”和“单选”。

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  not_multiple: 'Radio',
'Choose the one that applies'

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  add_question: 'Add question',
'Add a question'
英语名词是单数还是复数一定要显性地表达出来，所以如果context是可以添加多个问题就改成：
'Add questions'

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  please_add_question: 'Please add question',
同上要确定`question`的单复数

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  repeat: 'Repeat',
可以理解`repeat`是动作的重复，`duplicate`是值的重复，你按需修改

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  update_questionnaire: 'Update questionnaire',
要加`a`

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  update_questionnaire_success: 'Questionnaire updated successfully!',
时态和量词
'A questionnaire has been created successfully!'
这里是完成时

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  delete_questionnaire: 'Delete questionnaire',
量词

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  preview_questionnaire: 'Preview questionnaire',
这里应该是特制
`Preview the questionnaire`

2023-06-16 07:56 UTC, PapayaHUANG commented on translation/en-US.ts
> +  delete_questionnaire_success: 'Delete questionnaire successfully!',
时态同上

2023-06-16 14:18 UTC, Darrenjoe commented on components/Activity/QuestionnairePreview.tsx
> +      </Form.Group>
这里源码是为了将li的序号与输入框对齐做的处理

2023-06-16 15:35 UTC, TechQuery requested changes

2023-06-16 15:35 UTC, TechQuery commented on components/Activity/QuestionnairePreview.tsx
> +    index: number,
```suggestion
```

2023-06-16 15:35 UTC, TechQuery commented on components/Activity/QuestionnairePreview.tsx
>            <Form.Label></Form.Label>
```suggestion
          <Form.Label />
```

2023-06-16 15:35 UTC, TechQuery commented on components/Activity/QuestionnaireTable.tsx
> +      <div className="container-fluid">
`<Container fluid>`

2023-06-17 08:36 UTC, TechQuery requested changes

2023-06-17 08:36 UTC, TechQuery commented on components/Activity/QuestionnairePreview.tsx
> +          <a className="text-primary ms-2"> {t('personal_profile')}</a>
```suggestion
        {t('please_complete_all_mandatory_fields_before_you_proceed')}

        <Link href="https://ophapiv2-demo.authing.cn/u" passHref>
          <a className="text-primary ms-2">{t('personal_profile')}</a>
```

2023-06-17 08:36 UTC, TechQuery commented on components/Activity/QuestionnairePreview.tsx
> +  onSubmit?: (data: Question[]) => void;
```suggestion
  onSubmit?: (data: Question[]) => any;
```
（下同）

2023-06-17 08:36 UTC, TechQuery commented on components/Activity/QuestionnaireTable.tsx
> +                  <td>{typeMap[type || '--']}</td>
```suggestion
                  <td>{typeMap[type] || '--'}</td>
```
对象取不到值自然就回退到 `||` 后面的值了。

**表达式求值**和**视图显示**是两个层面的事，混为一谈会导致思路不清、代码复杂。

2023-06-17 08:57 UTC, Darrenjoe commented on components/Activity/QuestionnaireTable.tsx
> +                  <td>{typeMap[type || '--']}</td>
好的，但这里type类型是个可选枚举, “undefined”不能作为索引类型使用，需要先判断type存在

2023-06-17 09:56 UTC, TechQuery commented on components/Activity/QuestionnaireTable.tsx
> +                  <td>{typeMap[type || '--']}</td>
> 好的，但这里type类型是个可选枚举, “undefined”不能作为索引类型使用，需要先判断type存在

那可以在解构声明时给一个默认值

2023-06-17 10:02 UTC, TechQuery approved these changes

2023-06-17 10:17 UTC, Darrenjoe commented on components/Activity/QuestionnaireTable.tsx
> +                  <td>{typeMap[type || '--']}</td>
啊，怎么没想到，好的

2023-06-17 11:22 UTC, PapayaHUANG approved these changes

2023-06-17 14:34 UTC, TechQuery requested changes

2023-06-17 14:34 UTC, TechQuery commented on components/Activity/QuestionnaireCreate.tsx
> +      </div>
```suggestion
      <Form className="container-fluid" onSubmit={handleSubmit}>
        <Row as="ul" className="list-unstyled w-100 align-items-end g-3">
          <Col as="li" sm={4}>
            <Form.Group className="w-20" controlId="id">
              <Form.Label>
                {t('question_id')}
                {t('quote_required')}
              </Form.Label>
              <Form.Control name="id" required />
            </Form.Group>
          </Col>
          <Col as="li" sm={8}>
            <Form.Group className="flex-grow-1" controlId="title">
              <Form.Label>
                {t('question_description')}
                {t('quote_required')}
              </Form.Label>
              <Form.Control name="title" required />
            </Form.Group>
          </Col>
          <Col as="li" sm={4}>
            <Form.Group controlId="type">
              <Form.Label>{t('question_type')}</Form.Label>
              <Form.Select name="type">
                <option value="text">{t('text')}</option>
                <option value="url">{t('link')}</option>
              </Form.Select>
            </Form.Group>
          </Col>
          <Col as="li" sm={8}>
            <Form.Group controlId="options">
              <Form.Label>{t('option_config')}</Form.Label>
              <BadgeInput name="options" placeholder={t('tag_placeholder')} />
            </Form.Group>
          </Col>
          <Col as="li" sm={2}>
            <Form.Group controlId="multiple">
              <Form.Label>{t('whether_multiple')}</Form.Label>
              <Form.Check className="mx-2" type="switch" name="multiple" />
            </Form.Group>
          </Col>
          <Col as="li" sm={2}>
            <Form.Group key="required">
              <Form.Label>{t('whether_required')}</Form.Label>
              <Form.Check className="mx-2" type="switch" name="required" />
            </Form.Group>
          </Col>
          <Col sm={8} className="text-end">
            <Button className="px-5 " type="submit" variant="success">
              {t('add_question')}
            </Button>
          </Col>
        </Row>
      </Form>
```

2023-06-17 14:34 UTC, TechQuery commented on components/Activity/QuestionnaireTable.tsx
> +  },
```suggestion
const typeMap = () => ({
  text: t('text'),
  url: t('link'),
});

export const QuestionnaireTable: FC<QuestionnaireTableProps> = observer(
  ({ questionnaire, onDelete, onMove }) => (
    <Container fluid>
      <Table responsive className="my-3">
        <thead>
          <tr>
            <th>#</th>
            <th>{t('question_id')}</th>
            <th>{t('question_description')}</th>
            <th>{t('question_type')}</th>
            <th>{t('option_config')}</th>
            <th>{t('whether_multiple')}</th>
            <th>{t('whether_required')}</th>
            <th>{t('operation')}</th>
          </tr>
        </thead>
        <tbody>
          {questionnaire.map(
            (
              { id, title, options, multiple, type = 'text', required },
              index,
              { length },
            ) => (
              <tr key={id}>
                <td>{index + 1}</td>
                <td>{id}</td>
                <td>{title}</td>
                <td>{typeMap()[type] || '--'}</td>
                <td>{options?.join(';') || '--'}</td>
                <td>
                  {options
                    ? multiple
                      ? t('multiple')
                      : t('not_multiple')
                    : '--'}
                </td>
                <td>{required ? t('yes') : t('no')}</td>
                <td>
                  <Button variant="link" onClick={() => onDelete(id!)}>
                    {t('delete')}
                  </Button>

                  {!!index && (
                    <Button variant="link" onClick={() => onMove(id!, -1)}>
                      {t('move_up')}
                    </Button>
                  )}
                  {index !== length - 1 && (
                    <Button variant="link" onClick={() => onMove(id!, 1)}>
                      {t('move_down')}
                    </Button>
                  )}
                </td>
              </tr>
            ),
          )}
        </tbody>
      </Table>
    </Container>
  ),
```

2023-06-17 14:36 UTC, TechQuery approved these changes

2023-06-17 14:37 UTC, merged