[add] rewrite management page of Github repos
kaiyuanshe/OpenHackathon-Web pull request #175
Opened 2023-06-02 06:52 UTC by PapayaHUANG

- [ ] Labels
- [x] Assignees
- [x] Reviewers

Closes #125 

没写完

我的问题：
1. 我有参考`activityModel`和已经写好的`gitModel`，但是有太多细节不知道了，所以写不出来put方法。
2. 我这个应用场景如何使用postman加token测试API？

2023-06-16 04:18 UTC, PapayaHUANG commented
问题：
1. 后端delete方法有问题，暂时不能用。具体见https://github.com/kaiyuanshe/open-hackathon-api/issues/373
2. 原来的`git`这个model以及`Card.tsx`这两个文件是在`activity`和`team`两个路由下都使用的。我新写的`templateRepo`这个model和原本的`git`调用的是不一样的API，而我不知道`team`路由下想要实现怎么样的展示，就保留了以`git`这个model为基础在`team`路由下的原本实现，只修改了这个issue下的展示。
3. 在测试`team`路由的时候发现了bug，具体见https://github.com/kaiyuanshe/OpenHackathon-Web/issues/177

@TechQuery 
请你愉快地做code review吧～

2023-06-16 14:58 UTC, TechQuery requested changes

2023-06-17 18:25 UTC, TechQuery commented
@PapayaHUANG 把 #170 一起改一下吧

2023-06-18 02:19 UTC, PapayaHUANG commented on pages/activity/[name]/manage/git.tsx
> +    let { show, selectedIds } = this;
![image](https://github.com/kaiyuanshe/OpenHackathon-Web/assets/70144378/8f3ce678-a395-41c7-ab41-27a213fe667a)

这样写会报错？

2023-06-18 02:20 UTC, PapayaHUANG commented on pages/activity/[name]/manage/git.tsx
> +              <Button variant="danger" type="submit" className="me-2">
啊 我怎么老是犯这个错 哎 papa 叹气

2023-06-18 02:39 UTC, PapayaHUANG commented on components/Git/Modal.tsx
> +  inputField = { label: `${t('address')}`, text: `${t('url')}`, value: '' };
我为什么总是套两层？？？

2023-06-18 09:40 UTC, TechQuery commented on pages/activity/[name]/manage/git.tsx
> +    let { show, selectedIds } = this;
> ![image](https://github.com/kaiyuanshe/OpenHackathon-Web/assets/70144378/8f3ce678-a395-41c7-ab41-27a213fe667a)
> 
> 这样写会报错？

应该是 `this.selectedId = value`，因为解构可观察数据后，对应变量或常量都只具有之前的值，而没有可观察性。

2023-06-18 15:33 UTC, TechQuery requested changes

2023-06-18 15:33 UTC, TechQuery commented on models/TemplateRepo.ts
> +  }
要兼容增、改，参考：

https://github.com/kaiyuanshe/OpenHackathon-Web/blob/8b3e868d6ec2d7183e02ecb6d59863c55425673f/models/Award.ts#L48-L55

2023-06-25 15:36 UTC, TechQuery requested changes

2023-06-25 15:36 UTC, TechQuery commented on translation/zh-CN.ts
> +  for_example: '例如:',
```suggestion
  for_example: '例如：',
```

2023-06-25 15:36 UTC, TechQuery commented on translation/en-US.ts
> +  for_example: 'For example:',
```suggestion
  for_example: 'For example: ',
```

2023-06-25 15:36 UTC, TechQuery commented on components/Git/GitTeamCard.tsx
> +export const GitTeamCard: FC<TeamCardProps> = observer(
```suggestion
export const GitTeamCard: FC<GitTeamCardProps> = observer(
```

2023-06-25 15:36 UTC, TechQuery commented on components/Git/Modal.tsx
> +                  required
```suggestion
                  required
                  placeholder={
                    t('for_example') +
                    'https://github.com/idea2app/React-MobX-Bootstrap-ts'
                  }
                  onChange={({ currentTarget: { value } }) =>
                    (this.inputField.value = value)
                  }
```

2023-06-25 15:36 UTC, TechQuery commented on pages/activity/[name]/manage/git.tsx
>      for (const id of selectedIds) await this.store.deleteOne(id);
必要空格不要删

2023-06-26 19:09 UTC, TechQuery requested changes

2023-06-28 10:00 UTC, TechQuery approved these changes

2023-06-28 10:03 UTC, merged