[fix] delete noopener because of target="_blank"
kaiyuanshe/OpenHackathon-Web pull request #180
Opened 2023-06-28 14:00 UTC by tianheg

Checklist（清单）:

- [x] Labels
- [x] Assignees
- [x] Reviewers

移除 rel 中的 noopener，根据 [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target) 可知：当设置 `target="_blank"` 时，`rel="noopener"`已经包含在内了

2023-06-28 14:15 UTC, tianheg commented
> 建议一次性修复多个小问题，PR 过小（个位行数修改，紧急修复除外）、过大（净增长行超过 400 行，自动生成的文件除外）都不太好。

好，那这个 PR 就暂时放着吧。我这个星期会把“优化小屏幕适配”这个 issue 关掉

2023-06-28 16:13 UTC, TechQuery commented
> 好，那这个 PR 就暂时放着吧。我这个星期会把“优化小屏幕适配”这个 issue 关掉

关联一下 issue

2023-07-02 11:30 UTC, tianheg commented
@TechQuery 可以 review 了

2023-07-02 12:56 UTC, TechQuery requested changes

2023-07-02 12:56 UTC, TechQuery commented on components/Activity/ActivityEditor.tsx
> +            <Form.Control name="ribbon" type="text" defaultValue={ribbon} />
```suggestion
            <Form.Control name="ribbon" defaultValue={ribbon} />
```

2023-07-02 12:56 UTC, TechQuery commented on components/Activity/ActivityManageFrame.tsx
> +                      style={{ height: '16px', width: '16px' }}
```suggestion
                      style={{ height: '1rem', width: '1rem' }}
```

2023-07-02 12:56 UTC, TechQuery commented on components/Message/MessageList.tsx
> +          </td>
此处没必要改

2023-07-02 12:56 UTC, TechQuery commented on components/Message/MessageModal.tsx
> +              required
```suggestion
              as="textarea"
              name="content"
              required
              defaultValue={content}
```

2023-07-02 12:56 UTC, TechQuery commented on components/Team/TeamWorkList.tsx
> +              </div>
```suggestion
              <time
                className="d-block p-2 text-truncate"
                title={t('update_time')}
                dateTime={updatedAt}
              >
                <FontAwesomeIcon
                  className="text-success me-2"
                  icon={faCalendarDay}
                />
                {new Date(updatedAt).toLocaleString()}
              </time>
```

2023-07-02 13:38 UTC, tianheg commented
@TechQuery 都解决了

2023-07-02 13:52 UTC, TechQuery approved these changes

2023-07-02 13:53 UTC, merged