Fixed activity detail not triggering reminders in 2 cases
kaiyuanshe/OpenHackathon-Web pull request #194
Opened 2023-08-25 15:05 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #193

2023-08-25 15:49 UTC, TechQuery requested changes

2023-08-25 15:49 UTC, TechQuery commented on components/Activity/ActivityEditor.tsx
> +              defaultValue={this.detailHTML}
既然是默认值，就使用接口取到的值。

2023-08-25 15:49 UTC, TechQuery commented on components/Activity/ActivityEditor.tsx
> +              defaultValue={this.detailHTML}
```suggestion
              value={this.detailHTML}
```
默认值只会在初始化的时候赋值一次，不可能随着值的改变而改变。

2023-08-27 00:53 UTC, huoyueyuyuan commented on components/Activity/ActivityEditor.tsx
> +              defaultValue={this.detailHTML}
我查了下， 有个 componentDidMount() 方法。 它是在组件渲染后执行一次性的初始化操作。  在第45行     this.detailHTML = detail || ''。
所以 我理解  this.detailHTML 是结合接口取到、最新的值 ，用它更合理。

2023-08-27 01:04 UTC, huoyueyuyuan commented on components/Activity/ActivityEditor.tsx
> +              defaultValue={this.detailHTML}
已改。 
但是我debug的时候，会随着 this.detailHTML的值变化而变化， 不理解为什么。

2023-08-27 01:46 UTC, huoyueyuyuan commented on components/Activity/ActivityEditor.tsx
> +              onChange={code => (this.detailHTML = code === '<br>' ? '' : code)}
写了 isEmptyHTML方法来判断， 不知道是否恰当。

2023-08-27 06:01 UTC, TechQuery commented on components/Activity/ActivityEditor.tsx
> +              defaultValue={this.detailHTML}
> 我查了下， 有个 componentDidMount() 方法。 它是在组件渲染后执行一次性的初始化操作。  在第45行     this.detailHTML = detail || ''。
> 所以 我理解  this.detailHTML 是结合接口取到、最新的值 ，用它更合理。

你的理解没错，但此处确实是完全不需要更新它，直接用 `detail` 就更简洁。

2023-08-27 06:12 UTC, TechQuery requested changes

2023-08-27 06:12 UTC, TechQuery commented on components/Activity/ActivityEditor.tsx
> +};
你自己想出这种思路挺不错的，但这样会重复加载很多资源；同时如果只上传了图片，你就拿不到任何文字。

所以我觉得这里其实不用做这么复杂的 HTML 检测，我们只需要保证调接口的时候不报错，用户删空了内容自己负责就行了。

2023-08-27 13:09 UTC, TechQuery requested changes

2023-08-27 13:09 UTC, TechQuery commented on .husky/pre-push
> +#npm run build
```suggestion
npm run build
```

2023-08-27 13:09 UTC, TechQuery approved these changes

2023-08-27 13:13 UTC, merged