feat: use FilePreview display the team's work
kaiyuanshe/OpenHackathon-Web pull request #199
Opened 2023-09-26 11:29 UTC by CodeByZack

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes [#172](https://github.com/kaiyuanshe/OpenHackathon-Web/issues/172)

2023-09-26 11:33 UTC, TechQuery approved these changes

2023-09-27 01:25 UTC, TechQuery requested changes

2023-09-27 01:25 UTC, TechQuery commented on package.json
> +    "mobx-restful-table": "^1.1.4",
更新包版本需要重新执行 `pnpm i`，否则流水线就会因 lock 文件过时而挂掉：
 https://github.com/kaiyuanshe/OpenHackathon-Web/actions/runs/6320126288/job/17162176183#step:3:1

2023-09-27 01:39 UTC, CodeByZack commented on package.json
> +    "mobx-restful-table": "^1.1.4",
我还特意没有提交lock文件

2023-09-27 09:04 UTC, TechQuery approved these changes

2023-09-27 09:06 UTC, merged