feat: add mobx-strapi
kaiyuanshe/OpenHackathon-Web pull request #209
Opened 2024-02-22 09:16 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #204

2024-02-24 09:08 UTC, TechQuery requested changes

2024-02-24 09:08 UTC, TechQuery commented on package.json
> +    "mobx-strapi": "^0.4.5",
升级到 0.5 才能兼容新升级的标准语法：https://github.com/idea2app/MobX-RESTful/blob/main/wrapper%2FStrapi%2FReadMe.md

2024-02-24 14:11 UTC, luojiyin1987 commented on package.json
> +    "mobx-strapi": "^0.4.5",
已经升级 0.5.0， 不过在 npm 是 0.4.5
![image](https://github.com/kaiyuanshe/OpenHackathon-Web/assets/6524977/e866242d-700e-44d4-bd74-b0fc86c21561)

2024-04-17 07:24 UTC, TechQuery requested changes
请把整个项目运行起来，看看控制台有没有任何网络接口报错、在后台添加的数据前台能不能显示出来。

2024-04-17 07:24 UTC, TechQuery commented on models/Activity/Award.ts
> +import sessionStore, { strapiClient } from '../User/Session';
这个模块里面没有导出 `strapiClient`，TypeScript 应该也提示你了。

2024-04-17 07:24 UTC, TechQuery commented on models/Activity/Award.ts
> +export class AwardModel extends Stream<Award>(StrapiListModel) {
```suggestion
export class AwardModel extends StrapiListModel<Award> {
```
Strapi 有能定位到具体页数的分页参数，不需要 `Stream` 流式加载。

2024-04-17 07:24 UTC, TechQuery commented on models/Activity/Award.ts
> -  client = sessionStore.client;
此处不要改动，已经配置好登录验证机制的 API 客户端就是放在这个 store 上的。

2024-05-09 08:21 UTC, luojiyin1987 commented on models/Activity/Award.ts
> +export class AwardModel extends Stream<Award>(StrapiListModel) {
看不懂上面的两次修改

2024-05-09 10:24 UTC, TechQuery commented on models/Activity/Award.ts
> +export class AwardModel extends Stream<Award>(StrapiListModel) {
> 看不懂上面的两次修改

以前是附加流式加载特性，需要用 mixin（混入）的写法，也就是单继承语言实现多继承。

但 Strapi 不需要流式加载，就直接继承基类即可。

2024-05-13 03:38 UTC, luojiyin1987 commented on models/Activity/Award.ts
> -  client = sessionStore.client;
这我也看不懂了

2024-05-13 19:35 UTC, TechQuery commented on models/Activity/Award.ts
> -  client = sessionStore.client;
> 这我也看不懂了

先说说你个人的理解。

2024-05-22 13:35 UTC, luojiyin1987 commented on models/Activity/Award.ts
> -  client = sessionStore.client;
原来25 26 行代码是否要改动？ 我已经迷糊了。

2024-05-22 13:42 UTC, TechQuery commented on models/Activity/Award.ts
> -  client = sessionStore.client;
> 原来25 26 行代码是否要改动？ 我已经迷糊了。 

![Screenshot_2024-05-22-21-41-41-623_com.github.android-edit.jpg](https://github.com/kaiyuanshe/OpenHackathon-Web/assets/19969570/22718f62-f470-41bd-8baf-b715aa346979)

2024-05-23 15:14 UTC, luojiyin1987 commented on models/Activity/Award.ts
> -  client = sessionStore.client;
现在遇到  类型“AwardModel”上不存在属性“baseURI 的报错

2024-05-24 12:29 UTC, TechQuery commented on models/Activity/Award.ts
> -  client = sessionStore.client;
> 此处不要改动，已经配置好登录验证机制的 API 客户端就是放在这个 store 上的。

关于 client 的问题是我昏头了，你改为 `strapiClient` 是对的，是我在迁移阶段还没把 client 移到 `sessionStore` 上。

2025-04-03 12:41 UTC, TechQuery commented
No more Strapi for Back-end API.

2025-04-03 12:41 UTC, closed without merging

2025-04-03 13:15 UTC, luojiyin1987 commented
那换成什么？   @TechQuery

2025-04-03 14:34 UTC, TechQuery commented
> 那换成什么？   @TechQuery 

已经换了，换成上游库：#213