加左侧导航栏
kaiyuanshe/OpenHackathon-Web pull request #22
Opened 2020-12-27 13:41 UTC by gakki88

2020-12-28 13:44 UTC, TechQuery requested changes

2020-12-28 13:44 UTC, TechQuery commented on src/component/Navbar.tsx
> +        <>
**组件 DOM 结构**首层没有多个节点，可以删掉 `<></>` **片段节点**（下同）

2020-12-30 10:51 UTC, TechQuery requested changes

2020-12-30 10:51 UTC, TechQuery commented on src/model/User.ts
> +            hackathon_name: hackathon_name
此处可简写 —— http://es6-features.org/#PropertyShorthand

2020-12-30 10:51 UTC, TechQuery commented on src/page/Activity/ManageParticipant.tsx
> +                            <ToggleField type="checkbox"> </ToggleField>
JSX 没有子节点的标签可用**XML 自闭合标签**语法 —— 
```JSX
<ToggleField type="checkbox" />
```
（下同）

2020-12-30 10:51 UTC, TechQuery commented on src/page/Activity/ManageParticipant.tsx
> +                                    {['未审核', '通过', '拒绝', '自动通过'].map(
**常量数组**最好提到本模块文件最顶级

2020-12-30 10:51 UTC, TechQuery commented on src/model/User.ts
> +        return body;
某次活动 registration 的方法应该放到 `ActivityModel`，并注意：

1. 设置一个专用的 observable 属性来接收接口返回的数据，否则 UI 难以使用
2. 包含异步的方法要加 `@loading` 装饰器，来控制 `loading` 属性的切换

2021-01-01 18:34 UTC, gakki88 commented on src/page/Activity/ManageParticipant.tsx
> +                            <ToggleField type="checkbox"> </ToggleField>
需要留有两标签之间的空格才能显示出来，自闭合的显示不出来

2021-01-02 07:07 UTC, TechQuery commented on src/page/Activity/ManageParticipant.tsx
> +                            <ToggleField type="checkbox"> </ToggleField>
间距用样式来做，如 `className="mr-2"`

2021-01-04 10:23 UTC, TechQuery requested changes

2021-01-04 10:23 UTC, TechQuery commented on src/page/Activity/ManageParticipant.tsx
> +            });
根据 `activity` 的一个属性判断调用 `activity` 的哪个方法，两个方法的传参和返回值又一致，内部逻辑也非常像，就非常适合合并~

即便两个方法不那么一致，也不要把**与数据紧密相关的逻辑**放在视图层，而要在**模型层**新建一个封装方法，视图层尽量只管从用户操作中拿数据，然后显示返回的结果。

2021-01-04 10:23 UTC, TechQuery commented on src/page/Activity/ManageParticipant.tsx
> +                    checked={activity.config?.auto_approve}
在**同一函数内多次访问的对象成员**，最好**在函数开头解构为本地变/常量**。尤其对 `@watch`、`@observable` 这些装饰器包装为 getter、setter 属性的，解构只调用一次 getter 方法，反复用 `.` 取对象成员会多次调用。

2021-01-04 10:23 UTC, TechQuery commented on src/page/Activity/ManageParticipant.tsx
> +                                    <option selected>{status[e.status]}</option>
在迭代**回调参数处解构**会让函数体中的 JSX 代码更简洁，也方便后期体积变大后提取成独立的类方法。

2021-01-17 18:53 UTC, gakki88 commented on src/model/User.ts
> +    user: Partial<Omit<User, 'registration' & 'likes'>>;
感觉没什么不一样

2021-01-18 16:15 UTC, TechQuery approved these changes

2021-01-18 16:16 UTC, merged