feature: create team
kaiyuanshe/OpenHackathon-Web pull request #30
Opened 2021-06-24 02:45 UTC by rabbitom

创建团队的前提条件：黑客松已上线，已报名，活动已开始

2021-06-24 09:32 UTC, TechQuery commented on src/model/Team.ts
> +    }
可以合成一个方法，参考：

https://github.com/kaiyuanshe/OpenHackathon-Web/blob/master/src/model/Activity.ts#L124-L139

2021-06-24 09:36 UTC, TechQuery requested changes

2021-06-24 09:36 UTC, TechQuery commented on src/model/Team.ts
> +    }
可以合成一个方法，参考：

https://github.com/kaiyuanshe/OpenHackathon-Web/blob/master/src/model/Activity.ts#L124-L139

2021-06-24 09:36 UTC, TechQuery commented on src/page/Team.tsx
> +                            </Form>
本文件是**团队详情页**，**团队编辑表单**需要新建一个页面组件模块、路由

2021-06-25 02:44 UTC, rabbitom commented on src/model/Team.ts
> +    }
已修改

2021-06-25 02:46 UTC, rabbitom commented on src/page/Team.tsx
> +                            </Form>
已修改

2021-06-26 06:00 UTC, TechQuery approved these changes

2021-06-26 06:07 UTC, merged