feature: load team members
kaiyuanshe/OpenHackathon-Web pull request #36
Opened 2021-06-27 02:55 UTC by rabbitom

[在团队详情页中展示团队成员列表](https://hackathon.kaiyuanshe.cn/#team?activity=helloworld&tid=04a44f6c-0f9e-41f1-8802-adb0fe47b343)
team members不会在查询team时返回，需要调用专门的接口/team/{teamId}/member(s)，然后再调用users/{userId}获取用户信息
先review一下team member的model设计是否OK

work in progress #32

2021-06-29 08:56 UTC, TechQuery requested changes

2021-06-29 08:56 UTC, TechQuery commented on src/page/Team/Detail.tsx
> +            this.members = await activity.team.members.getNextPage({}, true);
此处逻辑可放入 `team.getOne()`

2021-06-29 08:56 UTC, TechQuery commented on src/page/Team/Detail.tsx
> +        const loading = activity.loading || (activity.team && activity.team.loading);
`activity.team.current` 现在默认存在，可能需要你合并 master 分支最新代码

2021-06-30 03:30 UTC, rabbitom commented on src/page/Team/Detail.tsx
> +        const loading = activity.loading || (activity.team && activity.team.loading);
fixed

2021-06-30 03:32 UTC, rabbitom commented on src/page/Team/Detail.tsx
> +            this.members = await activity.team.members.getNextPage({}, true);
将boot team members移进getOne了，但getNextPage没有，逻辑上并不是每次查询团队详情都需要成员列表

2021-06-30 03:37 UTC, rabbitom commented
src/page/Team/Detail.tsx
```
    @watch
    role = '';

    @watch
    status = '';
```

希望通过watch role和status，在加入和退出团队操作完成后，及时更新界面，但界面并未变化

2021-06-30 10:21 UTC, TechQuery requested changes

2021-06-30 10:21 UTC, TechQuery commented on src/page/Team/Detail.tsx
> +                            }
过长的表单结构可以写到单独的方法中

2021-06-30 10:21 UTC, TechQuery commented on src/page/Team/Detail.tsx
> +        }
过长的分支最好提前 `return`

2021-07-08 04:45 UTC, rabbitom commented on src/page/Team/Detail.tsx
> +        }
fixed

2021-07-08 04:45 UTC, rabbitom commented on src/page/Team/Detail.tsx
> +                            }
fixed

2021-07-08 12:54 UTC, TechQuery approved these changes

2021-07-08 12:55 UTC, merged