feature: manage team members
kaiyuanshe/OpenHackathon-Web pull request #43
Opened 2021-07-10 07:04 UTC by rabbitom

团队管理员查看团队成员列表，并：
- 修改成员角色
- 审核通过加入团队的申请
- 删除团队成员

2021-07-10 08:48 UTC, TechQuery requested changes

2021-07-10 08:48 UTC, TechQuery commented on src/page/Team/Members.tsx
> +            }
这段逻辑最好放到 MobX 的方法里

2021-07-10 08:48 UTC, TechQuery commented on src/page/Team/Members.tsx
> +            member.status = TeamMemberStatus.approved;
此段同上

2021-07-10 08:48 UTC, TechQuery commented on src/page/Team/Members.tsx
> +                                this.tid
**URL 多参数拼接**尽量用[构造器](https://web-cell.dev/web-utility/modules/url.html#buildurldata)

2021-07-11 13:39 UTC, rabbitom commented on src/page/Team/Members.tsx
> +            }
fixed

2021-07-11 13:39 UTC, rabbitom commented on src/page/Team/Members.tsx
> +            member.status = TeamMemberStatus.approved;
fixed

2021-07-11 13:39 UTC, rabbitom commented on src/page/Team/Members.tsx
> +                                this.tid
fixed

2021-07-11 19:38 UTC, TechQuery approved these changes

2021-07-11 19:39 UTC, merged