Activity
kaiyuanshe/OpenHackathon-Web pull request #62
Opened 2022-04-01 06:34 UTC by ShakalakaB

2022-04-01 06:37 UTC, ShakalakaB commented
> 为啥要加 `.idea` 文件

因为我用webstorm

2022-04-01 06:37 UTC, ShakalakaB commented
> `.vercel` 为啥要删除

已有

2022-04-01 06:42 UTC, TechQuery requested changes

2022-04-01 06:42 UTC, TechQuery commented on components/layout/Layout.tsx
> +            <Image src="/nextjs.png" alt="Next Logo" width={48} />
没引入 React Bootstrap 的 `Image` 组件
![image](https://user-images.githubusercontent.com/19969570/161209340-e69c6624-1aea-47f1-a603-c786b709df8c.png)

2022-04-01 06:42 UTC, TechQuery commented on .gitignore
> -.vercel
这个不能删

2022-04-01 06:47 UTC, stevending1st commented on components/layout/MainNavigation.tsx
> +      </Nav>
添加链接【[新手帮助](https://github.com/kaiyuanshe/open-hackathon/wiki/%E5%BC%80%E6%94%BE%E9%BB%91%E5%AE%A2%E6%9D%BE%E5%B9%B3%E5%8F%B0%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97) 】

2022-04-01 06:47 UTC, stevending1st commented on components/layout/MainNavigation.tsx
> +        />
用原生 img

2022-04-01 06:48 UTC, stevending1st commented on .gitignore
> -.vercel
> 这个不能删

已有

2022-04-01 06:49 UTC, ShakalakaB commented on .gitignore
> -.vercel
已有，重复

2022-04-01 06:50 UTC, ShakalakaB commented on components/layout/Layout.tsx
> +            <Image src="/nextjs.png" alt="Next Logo" width={48} />
已引入

2022-04-02 18:11 UTC, TechQuery requested changes

2022-04-02 18:11 UTC, TechQuery commented on components/ActivityDetail.tsx
> +          <label className="col-lg-3 col-md-4">报名时段
可写成：
```jsx
<Col as="label" md={4} lg={3}></Col>
```

2022-04-02 18:11 UTC, TechQuery commented on components/ActivityDetail.tsx
> +          <a role="button" className="col-3 btn btn-success">报名</a>
https://react-bootstrap.github.io/components/buttons/

2022-04-02 18:11 UTC, TechQuery commented on components/ActivityDetail.tsx
> +}
简单的**时间格式化**可以用脚手架内置的工具库，以减少体积：https://web-cell.dev/web-utility/modules.html#formatDate

2022-04-02 18:11 UTC, TechQuery commented on components/ActivityDetail.tsx
> +export default ActivityDetail;
`export default` 可以直接写在上面声明处（下同）

2022-04-02 18:11 UTC, TechQuery commented on components/layout/Layout.tsx
> +const Layout : React.FC = (props) => {
此处 props 类型为 `PropsWithChildren`，且参数可直接解构

2022-04-02 18:11 UTC, TechQuery commented on pages/activity/[hackathonName].tsx
> +}
写在页面前面会利于阅读数据来源

2022-04-02 18:11 UTC, TechQuery commented on pages/activity/[hackathonName].tsx
> +  const activity: Activity = await request<Activity>('hackathon/' + hackathonName);
这两个常量的类型可智能推导，可省略

2022-04-05 09:16 UTC, ShakalakaB commented on components/layout/MainNavigation.tsx
> +      </Nav>
已加

2022-04-05 09:16 UTC, ShakalakaB commented on components/layout/MainNavigation.tsx
> +        />
可以，原因是？

2022-04-05 09:18 UTC, ShakalakaB commented on components/ActivityDetail.tsx
> +import { Media } from "../pages/api/core";
已修改

2022-04-05 09:19 UTC, ShakalakaB commented on components/ActivityDetail.tsx
> +  return <Container>
ok

2022-04-05 09:29 UTC, ShakalakaB commented on components/ActivityDetail.tsx
> +      </div>
ok

2022-04-05 09:30 UTC, ShakalakaB commented on components/ActivityDetail.tsx
> +          {activity.banners.map((banner: Media, index: number) => {
ok

2022-04-05 12:17 UTC, ShakalakaB commented on components/ActivityDetail.tsx
> +export default ActivityDetail;
arrow function 直接写上面不太ok

2022-04-05 17:15 UTC, TechQuery approved these changes

2022-04-05 17:28 UTC, merged

2022-05-17 03:16 UTC, Soecka commented on components/layout/MainNavigation.tsx
> +        />
> 用原生 img

好奇+1，lint 总标黄，好几个页面`[id].tsx  TeamCard.tsx`也是用的原生 img

2022-05-17 12:16 UTC, TechQuery commented on components/layout/MainNavigation.tsx
> +        />
我一直觉得 React Bootstrap 的 `<Image />` 最好用

2022-05-17 13:20 UTC, Soecka commented on components/layout/MainNavigation.tsx
> +        />
插播一条：现在浏览器原生支持 img loading=‘lazy’ 了
https://web.dev/browser-level-image-lazy-loading/

2022-05-17 18:35 UTC, TechQuery commented on components/layout/MainNavigation.tsx
> +        />
WebCell 用了一段时间了
https://github.com/EasyWebApp/BootCell/blob/3d30027a97fe0a8c4ab8fabc8dfef22aede04de7/source/Media/Image/index.tsx#L48