团队主页
kaiyuanshe/OpenHackathon-Web pull request #63
Opened 2022-04-04 12:06 UTC by stevending1st

2022-04-18 07:50 UTC, TechQuery requested changes

2022-04-18 07:50 UTC, TechQuery commented on components/TeamCard.tsx
> +        href={`/team?activity=${hackathonName}&tid=${id}`}
合并主分支后，把 `team` 放在 `activity/[name]/` 下，这样路由会顺一些。

2022-04-18 07:50 UTC, TechQuery commented on models/Team.ts
> +  'POWERPOINT' = 'powerpoint',
键名无需引号

2022-04-18 07:50 UTC, TechQuery commented on models/Team.ts
> +  updatedAt: string;
继承的父级有了

2022-04-18 07:50 UTC, TechQuery commented on models/Team.ts
> +  status: string;
后端文档此处是枚举值

2022-04-18 07:50 UTC, TechQuery commented on models/Team.ts
> +  type: string;
后端文档此处是枚举值

2022-04-18 07:50 UTC, TechQuery commented on pages/team/index.tsx
> +  console.log('team:', team);
日志删掉

2022-04-18 07:50 UTC, TechQuery commented on pages/team/index.tsx
> +  const [teamWorks, setTeamWorks] = useState<TeamWork[]>([...workList]);
state 默认值需要展开为新数组吗？

2022-04-18 07:50 UTC, TechQuery commented on pages/team/index.tsx
> +    })();
也写到上面为一个具名函数？

2022-04-18 07:50 UTC, TechQuery commented on pages/team/index.tsx
> +        <Container>
```jsx
<Container as="main" />
```

2022-04-18 07:50 UTC, TechQuery commented on pages/team/index.tsx
> +          </Card>
https://react-bootstrap.github.io/components/breadcrumb/

2022-04-18 07:50 UTC, TechQuery commented on pages/team/index.tsx
> +                        <a href={`/user/${id}`} className="text-primary">
用 `className="ms-2"` 替代 `{' '}`

2022-04-18 07:50 UTC, TechQuery commented on pages/team/index.tsx
> +                      <Col key={index} claaaName="my-3">
`key` 尽量用数据库 `id`

2022-04-18 07:50 UTC, TechQuery commented on pages/team/index.tsx
> +                            </video>
直接写 `<video src="xxx" />`，兼容性已经 IE 9+ 了

2022-04-23 17:38 UTC, stevending1st commented on pages/team/index.tsx
> +  const [teamWorks, setTeamWorks] = useState<TeamWork[]>([...workList]);
> state 默认值需要展开为新数组吗？

不清楚，为了保险，还是这样写。

2022-04-24 07:40 UTC, TechQuery commented on pages/team/index.tsx
> +  const [teamWorks, setTeamWorks] = useState<TeamWork[]>([...workList]);
感觉 hooks 总有些语法之外的注意点，心力全放在 API 上了

2022-04-24 07:50 UTC, TechQuery requested changes

2022-04-24 07:50 UTC, TechQuery commented on models/Team.ts
> +  type: string;
没改

2022-04-24 07:50 UTC, TechQuery commented on pages/activity/[name]/index.tsx
> +            {/* @ts-ignore */}
这么改会失效，之前的写法是 TS 的官方奇技淫巧

2022-04-24 07:50 UTC, TechQuery commented on pages/activity/[name]/team/[tid].tsx
> +import { redirect } from 'next/dist/server/api-utils';
外置 package 导入放相对路径导入的前面

2022-04-24 07:50 UTC, TechQuery commented on pages/activity/[name]/team/[tid].tsx
> +  if (!name || Array.isArray(name) || !tid || Array.isArray(tid)) push('/404');
`name`、`tid` 有可能是数组吗？

2022-04-24 07:50 UTC, TechQuery commented on pages/activity/[name]/team/[tid].tsx
> +                        </a>
和最后默认情况合一起

2022-04-24 12:52 UTC, stevending1st commented on pages/activity/[name]/index.tsx
> +            {/* @ts-ignore */}
这不是我的，我只是调了一个冲突。

2022-04-24 12:59 UTC, stevending1st commented on pages/activity/[name]/team/[tid].tsx
> +  if (!name || Array.isArray(name) || !tid || Array.isArray(tid)) push('/404');
> `name`、`tid` 有可能是数组吗？

nextjs 的类型

2022-04-24 13:00 UTC, stevending1st commented on pages/activity/[name]/team/[tid].tsx
> +import { redirect } from 'next/dist/server/api-utils';
> 外置 package 导入放相对路径导入的前面

已删除

2022-04-24 16:40 UTC, TechQuery approved these changes

2022-04-24 16:41 UTC, merged