2022 用户详情页
kaiyuanshe/OpenHackathon-Web pull request #64
Opened 2022-04-11 09:31 UTC by Soecka

Checklist（清单）:

- [add] UserDetail Component
- [add] UserDetail Page

2022-04-11 11:21 UTC, TechQuery requested changes
1. 删掉空文件：`components/UserActivityTab`
2. 删掉 `package-lock.json`，使用 Yarn
3. 在项目根目录执行：

```shell
chmod +x .husky/pre-commit
chmod +x .husky/pre-push
```

2022-04-11 11:21 UTC, TechQuery commented on components/UserDetails.tsx
> +} }) => {
**组件类型声明**应为：

```tsx
export interface UserDetailProps extends Session {
    className: string;
}
export const UserDetail: React.FC<UserDetailProps> = () => {}
```

1. 类型传参形式有误
2. 类型命名与组件一致，利于使用

2022-04-11 11:21 UTC, TechQuery commented on components/UserDetails.tsx
> +            <Container style={{ minWidth: '520px' }}>
1. 宽度让页面容器来控制，组件尽可能维持**自适应**
2. 如需控制，**尺寸单位**尽量用 `rem`

2022-04-11 11:21 UTC, TechQuery commented on components/UserDetails.tsx
> +                                            className={registerSource.includes(`social:github`) ? 'text-success fa-stack' : 'text-secondary fa-stack'}
类名重复部分提出来

2022-04-11 11:21 UTC, TechQuery commented on pages/user/[id].tsx
> +    return { props: { userInfo } }
需处理 ID 为空的情况，用户可能自己输入 URL，会让你的后端接口请求成为“拉列表”

2022-04-13 01:55 UTC, Soecka commented on components/UserDetails.tsx
> +} }) => {
Fix in this commit
https://github.com/kaiyuanshe/OpenHackathon-Web/pull/64/commits/f345739ab57e229471581058cf55cfd4f2ff5d53

2022-04-13 01:55 UTC, Soecka commented on components/UserDetails.tsx
> +            <Container style={{ minWidth: '520px' }}>
Fix in this commit
https://github.com/kaiyuanshe/OpenHackathon-Web/commit/f345739ab57e229471581058cf55cfd4f2ff5d53

2022-04-13 01:55 UTC, Soecka commented on components/UserDetails.tsx
> +                                            className={registerSource.includes(`social:github`) ? 'text-success fa-stack' : 'text-secondary fa-stack'}
Fix in this commit
https://github.com/kaiyuanshe/OpenHackathon-Web/commit/f345739ab57e229471581058cf55cfd4f2ff5d53

2022-04-13 01:55 UTC, Soecka commented on pages/user/[id].tsx
> +    return { props: { userInfo } }
Fix in this commit
https://github.com/kaiyuanshe/OpenHackathon-Web/commit/f345739ab57e229471581058cf55cfd4f2ff5d53

2022-04-13 07:55 UTC, TechQuery commented on components/UserDetails.tsx
> +            <Container style={{ minWidth: '520px' }}>
建议参考第 1 点实现，让外面容器来控制这个子组件的宽度

2022-04-13 13:27 UTC, Soecka commented on components/UserDetails.tsx
> +            <Container style={{ minWidth: '520px' }}>
> 建议参考第 1 点实现，让外面容器来控制这个子组件的宽度

好的呢，之前给一个固定宽度是为了避免窗口小于xs之后页面继续重重排，后来发现是chrome dev tool带来的影响。
![sasa](https://2021blogpic.oss-cn-beijing.aliyuncs.com/blog/image/chromedev.png)

2022-04-13 14:45 UTC, TechQuery commented on components/UserDetails.tsx
> +}: UserDetailProps) => {
前面声明了整个函数的类型，props 就无需单独声明了，TypeScript 能推导出来，你可以删了试试（下个 PR 再改）。

2022-04-13 14:45 UTC, TechQuery approved these changes

2022-04-13 14:45 UTC, TechQuery commented on components/UserDetails.tsx
> +}: UserDetailProps) => {
前面声明了整个函数的类型，props 就无需单独声明了，TypeScript 能推导出来，你可以删了试试（下个 PR 再改）。

2022-04-13 14:47 UTC, merged