2022 活动报名页
kaiyuanshe/OpenHackathon-Web pull request #67
Opened 2022-04-20 07:39 UTC by Soecka

- [add] Form Layout

2022-04-20 14:12 UTC, TechQuery requested changes

2022-04-20 14:12 UTC, TechQuery commented on pages/activity/[name]/register.tsx
> +          {label}
1. **数字前缀**优先用 `<ol><li /></ol>`：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/ol
2. `<label />` 的语义只用作**输入控件**的容器

2022-04-20 14:12 UTC, TechQuery commented on pages/activity/[name]/register.tsx
> +                <label htmlFor={value} key={value} className="form-check-label">
1. React `key` 属性应放在**迭代结构**的顶层容器上，而非内层结构
2. 如非必要，切勿禁用 ESLint 检查

2022-04-20 14:12 UTC, TechQuery commented on pages/activity/[name]/register.tsx
> +          </Row>
如果没有界面定制需求，优先用组件库实现，利于外观统一：
https://react-bootstrap.netlify.app/forms/layout/#form-grid

2022-04-22 10:54 UTC, TechQuery requested changes

2022-04-22 10:54 UTC, TechQuery commented on models/Question.ts
> +  type?: string;
类型可以详细为形如 `'text' | 'url'`

2022-04-22 10:54 UTC, TechQuery commented on pages/activity/[name]/register.tsx
> +    location.reload();
接上去是因为你没有 `/` 开头，是基于当前目录的相对路径。

但我们现在是**后端渲染**，直接用 HTML 4 的 `location.href = '/xxx'` 即可。

2022-04-22 10:54 UTC, TechQuery commented on pages/activity/[name]/register.tsx
> +    return options ? (
箭头函数可省略 `{ return }`

2022-04-22 10:54 UTC, TechQuery commented on pages/activity/[name]/register.tsx
> +            <Link href="https://ophapiv2-demo.authing.cn/u">
少个 `passHref` 属性

2022-04-22 10:54 UTC, TechQuery commented on pages/activity/[name]/register.tsx
> +              <a className="text-primary">{' ' + '个人资料'}</a>
间距用 `className="ms-2"`，不要硬拼字符串

2022-04-22 10:54 UTC, TechQuery commented on pages/user/[id].tsx
> +
由此可见你本地是**类 UNIX 系统**，且 **Git hooks 脚本**没执行权限，提交时没执行格式化，需要在**项目根目录**执行一下：

```shell
chmod +x .husky/pre-commit
chmod +x .husky/pre-push
git add .
```

2022-04-22 10:54 UTC, TechQuery commented on yarn.lock
> +
该文件冲突合并错误，删掉 `yarn.lock` 后重新执行：
```shell
yarn install
git add .
```

2022-04-22 12:30 UTC, Soecka commented on pages/activity/[name]/register.tsx
> +            <Link href="https://ophapiv2-demo.authing.cn/u">
好的呢，Eslint检查没有报错，可能是因为子元素是<a>?之前如果是Link包裹Button不passref是会报错的

2022-04-22 18:40 UTC, TechQuery commented on pages/user/[id].tsx
> +
就是要提交时 lint + format

2022-04-22 18:42 UTC, TechQuery commented on yarn.lock
> +
如有包更新，有差异正常，只是上一次提交里有处理冲突错误导致的语法错误

2022-04-22 18:44 UTC, TechQuery approved these changes

2022-04-22 18:46 UTC, merged