Add html for create activity
kaiyuanshe/OpenHackathon-Web pull request #71
Opened 2022-04-24 14:34 UTC by ShakalakaB

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2022-04-24 16:48 UTC, TechQuery requested changes

2022-04-24 16:48 UTC, TechQuery commented on pages/activity/create.tsx
> +              </InputGroup>
抽个组件，参考：https://github.com/kaiyuanshe/OpenHackathon-Web/blob/master/src/component/TimeRange.tsx

2022-05-07 12:30 UTC, TechQuery requested changes

2022-05-07 12:30 UTC, TechQuery commented on models/NameAvailability.tsx
> +export type { NameAvailability };
直接 `export interface` 即可

2022-05-07 12:30 UTC, TechQuery commented on models/Activity.ts
> +  // bannerUrls:  string[];
注释的无用代码删掉

2022-05-07 12:30 UTC, TechQuery commented on components/MyFilePicker.tsx
> +// import { Icon } from "idea-react/source/Icon";
直接写包名，无需具体路径

2022-05-07 12:30 UTC, TechQuery commented on components/MyFilePicker.tsx
> +export class MyFilePicker extends PureComponent<FilePickerProps, State> {
这个组件已拥有上传功能，就应该叫 `FileUploader`

2022-05-07 12:30 UTC, TechQuery commented on components/MyFilePicker.tsx
> +      const fileUrl: string = await this.uploadFile(file);
此处类型无需额外声明

2022-05-07 12:30 UTC, TechQuery commented on components/MyFilePicker.tsx
> +    const fileName: string = file.name;
此处类型无需额外声明

2022-05-07 12:30 UTC, TechQuery commented on components/MyFilePicker.tsx
> +        filename: fileName,
常量名可与对象键名同名，即可简写

2022-05-07 12:30 UTC, TechQuery commented on components/MyFilePicker.tsx
> +    );
这个可以合到上传工具函数中

2022-05-07 12:30 UTC, TechQuery commented on components/ActivityCreate.tsx
> +      ([] as string[]).concat(inputParams.bannerUrls ?? []),
写成**数组展开**语法

2022-05-07 12:30 UTC, TechQuery commented on components/ActivityCreate.tsx
> +import { string } from 'prop-types';
这是啥库？

2022-05-09 16:35 UTC, TechQuery requested changes

2022-05-09 16:35 UTC, TechQuery commented on components/ActivityCreate.tsx
> +    console.log(inputParams);
日志删掉（下同）

2022-05-09 16:35 UTC, TechQuery commented on pages/activity/[name]/index.tsx
> +    : activity.detail;
在赋值语句前用 `if` 评定属性存在性

2022-05-09 17:06 UTC, TechQuery requested changes

2022-05-09 17:06 UTC, TechQuery commented on models/Activity.ts
> +export interface ActivityFormData
视图层的数据结构声明在对应组件

2022-05-09 17:06 UTC, TechQuery commented on models/Activity.ts
> +  judgeEndedAt?: string;
如果一些字段提交时可选，最初声明类型的时候就写成可选的吧

2022-05-09 17:06 UTC, TechQuery commented on utils/time.ts
> +};
```suggestion
export const convertDatetime = (datetime = '') =>
  datetime && new Date(datetime).toLocaleString();
```

2022-05-09 17:06 UTC, TechQuery commented on utils/uploadFile.ts
> +  const uploadUrlRes = await requestClient<UploadUrl>(
此处可解构

2022-05-10 03:40 UTC, ShakalakaB commented on components/ActivityCreate.tsx
> +    await router.push(`/activity/${inputParams.name}`);
是个promise, 需要await

2022-05-10 03:43 UTC, ShakalakaB commented on components/ActivityCreate.tsx
> +      event.target as HTMLFormElement,
需要，删了报错

2022-05-10 06:09 UTC, ShakalakaB commented on models/Activity.ts
> +  judgeEndedAt?: string;
但我不确定首次创建model字段type,和发布时的type之间是否有区别，有可能发布时再次检查要求非空

2022-05-10 09:01 UTC, TechQuery commented on components/ActivityCreate.tsx
> +      event.target as HTMLFormElement,
> `event.currentTarget` 无需类型断言

你好好看看咱俩取的是否是同个属性……

2022-05-10 09:03 UTC, TechQuery commented on models/Activity.ts
> +  judgeEndedAt?: string;
通常不会这么干，真有问题再说

2022-05-10 09:06 UTC, TechQuery commented on components/ActivityCreate.tsx
> +            头图（必填,最多10张）
@ShakalakaB 看清楚我要求改的是什么符号…… 中文文案中应该全是**中文全角符号**才符合规范啊

> 中文逗号

2022-05-10 09:10 UTC, TechQuery requested changes

2022-05-10 09:10 UTC, TechQuery commented on models/NameAvailability.tsx
>  }
这个数据结构属于活动业务的一块，放到 `model/Activity.ts`

2022-05-10 09:10 UTC, TechQuery commented on utils/time.ts
> +  return datetime && new Date(datetime).toLocaleString();
return 前无其它逻辑可以简写为 [Lambda（箭头函数）表达式](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/Arrow_functions)

2022-05-11 03:36 UTC, ShakalakaB commented on components/ActivityCreate.tsx
> +      event.target as HTMLFormElement,
我当然看的懂
<img width="664" alt="Screen Shot 2022-05-11 at 11 36 35 AM" src="https://user-images.githubusercontent.com/32429379/167764148-3a40c09f-7ea5-4bb8-8174-c67d59364af1.png">
，

2022-05-11 03:59 UTC, ShakalakaB commented on components/ActivityCreate.tsx
> +const ActivityCreate: React.FC = () => {
达不到完全复用，之后如果写到修改页，复用到的地方会用这个

2022-05-11 09:05 UTC, TechQuery requested changes

2022-05-11 09:05 UTC, TechQuery commented on components/ActivityCreate.tsx
> +        <DateTimeInput label="评分时间(必填)" name="judge" required={true} />
省略 `={true}`（下同）

2022-05-11 09:05 UTC, TechQuery commented on components/DateTimeInput.tsx
> +  required = false,
此处无需默认值，没传就是 `undefined`，输入框接受的

2022-05-12 09:50 UTC, TechQuery approved these changes

2022-05-12 10:04 UTC, merged