2022 活动管理 奖项设置
kaiyuanshe/OpenHackathon-Web pull request #77
Opened 2022-05-14 18:55 UTC by Soecka

[add] award model , award page
[polish] administrator handleSubmit function

2022-05-14 18:57 UTC, Soecka commented on components/ActivityManageFrame.tsx
> +      <Col className="flex-fill ">
试图优化一下框架，下次再修改

2022-05-15 16:31 UTC, TechQuery requested changes

2022-05-15 16:31 UTC, TechQuery commented on pages/activity/[name]/manage/administrator.tsx
> +    }
事件来自 3 个不同的表单，逻辑本身无法复用，还是不要集中于一处。弹框中的提交逻辑可以先将弹框写为类组件，再放在其中成为其方法，外面的页面组件即可无需关心里面的复杂性。

2022-05-15 16:31 UTC, TechQuery commented on pages/activity/[name]/manage/award.tsx
> +  };
类型可以写成 `Partial<Award>`，尽量减少不一致

2022-05-15 16:31 UTC, TechQuery commented on pages/activity/[name]/manage/award.tsx
> +  };
我觉得相似性较低，建议不合

2022-05-15 16:31 UTC, TechQuery commented on pages/activity/[name]/manage/award.tsx
> +    });
直接这样不行？
```javascript
this.setState({ currentAward });
```

2022-05-15 16:31 UTC, TechQuery commented on pages/activity/[name]/manage/award.tsx
> +      awardList: awardList,
简写为 `{ awardList }`

2022-05-15 16:31 UTC, TechQuery commented on pages/activity/[name]/manage/award.tsx
> +              <tbody>{this.state.awardList.map(this.renderItem)}</tbody>
上方解构 `this.state`

2022-05-15 16:31 UTC, TechQuery commented on pages/activity/[name]/manage/award.tsx
> +    const { awardid } = event.currentTarget.dataset,
若 HTML 如下：
```html
<div data-award-id=""></div>
```
即可用**小驼峰命名**取值：
```javascript
div.dataset.awardId
```
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset#name_conversion

2022-05-16 01:33 UTC, Soecka commented on pages/activity/[name]/manage/administrator.tsx
> +      : firstCheckbox?.setCustomValidity('请选择至少一位管理员或裁判！');
```
Object.values(this.state.checked).some(check => 
check ? firstCheckbox?.setCustomValidity('')
      : firstCheckbox?.setCustomValidity('请选择至少一位管理员或裁判！'))
```
这样写貌似会出错，即使选中了还是会要求验证 ' 请选择至少一位管理员或裁判！'

2022-05-16 01:52 UTC, Soecka commented on pages/activity/[name]/manage/award.tsx
> +    });
会多出几项，应该问题不大，后面渲染表单我通过解构只取了想要的
```
createdAt: "2022-05-16T01:38:14.1850898Z"
description: "测试二等奖"
hackathonName: "api1234"
id: "24180133-6bb3-4f36-a742-cb1b4cb029bd"
name: "优秀团队二等奖"
pictures: null
quantity: 10
target: "team"
updatedAt: "2022-05-16T01:38:14.1852107Z"
```

2022-05-16 02:16 UTC, Soecka commented on pages/activity/[name]/manage/award.tsx
> +    const { awardid } = event.currentTarget.dataset,
Get!

2022-05-16 10:34 UTC, TechQuery commented on pages/activity/[name]/manage/administrator.tsx
> +      : firstCheckbox?.setCustomValidity('请选择至少一位管理员或裁判！');
```suggestion
    firstCheckbox?.setCustomValidity(
        Object.values(this.state.checked).some(check => check) ?
            '' : '请选择至少一位管理员或裁判！'
    );
```

2022-05-16 11:57 UTC, TechQuery requested changes

2022-05-16 11:57 UTC, TechQuery commented on components/ActivityAdministratorModal.tsx
> +    this.props.updateList();
上面可以解构

2022-05-16 14:03 UTC, Soecka commented on pages/activity/[name]/manage/administrator.tsx
> +      : firstCheckbox?.setCustomValidity('请选择至少一位管理员或裁判！');
脑子瓦特了，居然没想到……

2022-05-16 15:17 UTC, Soecka commented on components/ActivityAdministratorModal.tsx
> +    form.reset();
![middle_img_v2_dc22ec10-860b-4cc6-ae09-7216d3dbf3eg](https://user-images.githubusercontent.com/32708404/168625187-34d1597a-42dc-4966-b2bc-472ffeb34f34.jpg)
非常假，我之前没有用重构，是因为console.log()发现currentTarget为null，所以用target，但是target typescript会报错，所以给它定义了一个Form类型；后续查找资料https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget发现
 > Note: The value of event.currentTarget is only available while the event is being handled. If you [console.log()](https://developer.mozilla.org/en-US/docs/Web/API/console/log) the event object, storing it in a variable, and then look for the currentTarget key in the console, its value will be null.
Instead, you should either use console.log(event.currentTarget) to be able to view it in the console or use the [debugger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger) statement, which will pause the execution of your code thus showing you the value of event.currentTarget.

即使看不到,但是实际可以访问的,然而我观察控制台输出后发现,在请求后端数据后,event.CurrentTarget会变成null

2022-05-16 15:26 UTC, Soecka commented on components/ActivityAdministratorModal.tsx
> +    form.reset();
继续查找资料发现,可以使用event.persist(),但是React 17 persist不生效了
> 注意：

从 v17 开始，e.persist() 将不再生效，因为 SyntheticEvent 不再放入[事件池](https://zh-hans.reactjs.org/docs/legacy-event-pooling.html)中。

所以我打算先把event.currentTarget赋值给一个常量保存起来

2022-05-16 15:48 UTC, TechQuery commented on components/ActivityAdministratorModal.tsx
> +    form.reset();
所有对原生事件系统做包装的框架，都会在事件触发后销毁对节点对象的引用，防止内存泄露。

浏览器控制台对对象的打印是在展开详情时候读取数据，那时候内存里面已经变成了 `null`。只有打印具体字段才一定会显示出来。

2022-05-16 18:18 UTC, TechQuery approved these changes

2022-05-16 18:33 UTC, merged