活动修改
kaiyuanshe/OpenHackathon-Web pull request #79
Opened 2022-05-16 10:36 UTC by ShakalakaB

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2022-05-16 19:20 UTC, TechQuery requested changes

2022-05-16 19:20 UTC, TechQuery commented on components/ActivityEditor.tsx
> +}> = ({ submitHandler, isNameAvailable, activity }) => {
1. 组件类型独立声明
2. **事件回调**命名风格建议为 `onSubmit`，符合 HTML 惯例，且返回值类型为 `any` 兼容性更好

2022-05-16 19:20 UTC, TechQuery commented on components/ActivityEditor.tsx
> +  return (
**无状态函数组件**可省略 `{ return }`

2022-05-16 19:20 UTC, TechQuery commented on components/ActivityEditor.tsx
> +            readOnly={activity && true}
等价表达式 `!!activity`

2022-05-16 19:20 UTC, TechQuery commented on components/ActivityEditor.tsx
> +            defaultValue={activity?.tags ? activity.tags.join(' ') : ''}
该三目表达式可简写为 `activity?.tags.join(' ')`，因为 `defaultValue` 作为可选属性可为 `undefined`

2022-05-16 19:20 UTC, TechQuery commented on components/ActivityEditor.tsx
> +            defaultValue={activity?.banners.map(banner => banner.uri)}
箭头函数中可解构

2022-05-16 19:20 UTC, TechQuery commented on components/ActivityEditor.tsx
> +            defaultValue={activity ? activity.maxEnrollment : 0}
`activity?.maxEnrollment || 0`

2022-05-16 19:20 UTC, TechQuery commented on components/ActivityEditor.tsx
> +        Submit
目前统一为中文，国际化后面再做

2022-05-16 19:20 UTC, TechQuery commented on pages/activity/[name]/edit.tsx
> +import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next';
外置模块放最前面

2022-05-17 02:04 UTC, ShakalakaB commented on components/ActivityEditor.tsx
> +}> = ({ submitHandler, isNameAvailable, activity }) => {
"返回值类型为 `any `兼容性更好" : 目前这行代码Promise<void>兼容性够了，如果后续有不够，再逐步把类型升上去，不需要一次写到any，我觉得还是需要保持类型的意义

2022-05-17 12:14 UTC, TechQuery requested changes

2022-05-17 12:14 UTC, TechQuery commented on components/ActivityEditor.tsx
> +type activityEditorProps = {
类型命名采用 Java 风格的**大驼峰**

2022-05-18 07:12 UTC, ShakalakaB commented on components/ActivityEditor.tsx
> +}> = ({ submitHandler, isNameAvailable, activity }) => {
void比any更合适，目前这个submit没有任何返回，用void非常合适地告诉使用者此handler无return
any等于还要考虑返回情况

2022-05-18 13:31 UTC, TechQuery approved these changes

2022-05-18 13:32 UTC, merged