2022 活动管理 团队作品评奖页
kaiyuanshe/OpenHackathon-Web pull request #84
Opened 2022-06-18 14:45 UTC by Soecka

[add] Evaluation Page, simple UI structure

2022-09-14 19:34 UTC, TechQuery requested changes

2022-09-14 19:34 UTC, TechQuery commented on pages/activity/[name]/manage/evaluation.tsx
> +interface State {}
删掉空类型，后面我们会从 React state 迁移到 MobX，用作组件内外的状态管理。

2022-09-14 19:34 UTC, TechQuery commented on pages/activity/[name]/manage/evaluation.tsx
> +
```suggestion
export default class EvaluationPage extends PureComponent<
  InferGetServerSidePropsType<typeof getServerSideProps>
> {
```

2022-10-12 21:36 UTC, TechQuery requested changes

2022-10-12 21:36 UTC, TechQuery commented on pages/activity/[name]/manage/award.tsx
> +import { observer } from 'mobx-react';
第三方库放最上面

2022-10-12 21:36 UTC, TechQuery commented on pages/activity/[name]/manage/award.tsx
>        };
此处有变化，需合并主分支最新代码

2022-10-12 21:36 UTC, TechQuery commented on pages/activity/[name]/manage/evaluation.tsx
> +      };
合并主分支后，参考以下代码：

https://github.com/kaiyuanshe/OpenHackathon-Web/blob/b442bd301fbf796d77f777d3c11f600c5e019768/pages/activity/%5Bname%5D/manage/participant/index.tsx#L13-L19

2022-11-30 17:45 UTC, TechQuery requested changes

2022-11-30 17:45 UTC, TechQuery commented on components/Team/TeamAwardCard.tsx
> +        <Accordion.Body></Accordion.Body>
这里是没接口还是？

2022-11-30 17:45 UTC, TechQuery commented on models/Award.ts
> +  awardId: string;
用 `Record` 泛型简化

2022-11-30 17:45 UTC, TechQuery commented on pages/activity/[name]/manage/evaluation.tsx
> +  };
```suggestion
  handleReset = () => this.store.clearCurrent();
```
`<form />` 的 `reset` 事件已经清空了数据，无需再 `.reset()`

2022-11-30 17:45 UTC, TechQuery commented on pages/activity/[name]/manage/evaluation.tsx
> +  handleAssign = () => {};
没写完？

2022-11-30 17:45 UTC, TechQuery commented on pages/activity/[name]/manage/evaluation.tsx
> +    const data = formToJSON<NewData<AwardAssignment>>(form);
```suggestion
    const { awardStore, store } = this,
      form = event.currentTarget;
    const data = formToJSON<NewData<AwardAssignment>>(form);
```

2022-11-30 17:45 UTC, TechQuery commented on pages/activity/[name]/manage/evaluation.tsx
> +          )}
```suggestion
      <ul className="list-unstyled">
        {allItems.map(({ target, id, name, quantity }) =>
            (target === 'team') && 
              <li key={id} className="mx-2 my-3">{
                  awardTeamId ? (
              <Form.Check
                type="radio"
                key={id}
                label={name}
                name="awardId"
                value={id}
              />
            ) : name}
              </li>,
          )}
        </ul>
```
React 会自动忽略 JSX 中数组元素中的假值

2022-11-30 17:45 UTC, TechQuery commented on pages/activity/[name]/manage/evaluation.tsx
> +    return (
```suggestion
    const { resolvedUrl, params } = this.props.route;

    return (
```

2022-11-30 17:45 UTC, TechQuery commented on pages/activity/[name]/manage/evaluation.tsx
> +                  required
```suggestion
                  type="search"
                  id="teamSearch"
                  name="teamSearch"
                  required
                  aria-label="search team"
                  placeholder="团队名称"
```

2022-11-30 19:05 UTC, Soecka commented on components/Team/TeamAwardCard.tsx
> +        <Accordion.Body></Accordion.Body>
目前只完成了奖项分配功能，各个维度打分后续要分别在奖项设置页面和评奖页开发对应组件

2022-11-30 19:09 UTC, Soecka commented on pages/activity/[name]/manage/evaluation.tsx
> +  handleAssign = () => {};
已删除

2022-11-30 20:36 UTC, TechQuery approved these changes

2022-11-30 20:39 UTC, merged