add create Team
kaiyuanshe/OpenHackathon-Web pull request #91
Opened 2022-09-11 16:43 UTC by stevending1st

Checklist（清单）:
- 增加活动人数输入框限制
- 创建团队

- [x] Labels
- [ ] Assignees
- [x] Reviewers

2022-09-14 20:13 UTC, TechQuery requested changes

2022-09-14 20:13 UTC, TechQuery commented on components/ActivityEditor.tsx
> +          min={0}
```suggestion
          min={0}
          max={100000}
```

2022-09-14 20:13 UTC, TechQuery commented on components/TeamCreateModal.tsx
> +}
```suggestion
export interface TeamCreateProps {
  hackathonName: string;
  show: boolean;
  onClose: () => any;
}
```

2022-09-14 20:13 UTC, TechQuery commented on components/TeamEditor.tsx
> +};
```suggestion
export interface TeamEditorProps {
  team?: Team;
  checkName?: (name?: string) => Promise<boolean>;
  onSubmit: (event: FormEvent<HTMLFormElement>) => any;
}
```

2022-09-14 20:13 UTC, TechQuery commented on pages/activity/[name]/index.tsx
> +
```suggestion
```

2022-09-14 20:13 UTC, TechQuery commented on pages/activity/[name]/index.tsx
> +  return { props: { activity, teams, enrollmentStatus, myteam } };
```suggestion
  try {
    var { status } = await request<Enrollment>(
      `hackathon/${name}/enrollment`,
      'GET',
      undefined,
      { req, res },
    );
  } catch {}

  try {
    if (enrollmentStatus === 'approved')
      var myTeam = await request<Team>(`hackathon/${name}/team`, 'GET', undefined, { req, res });
  } catch {}

  return { props: { activity, teams, status, myTeam } };
```

2022-09-21 14:13 UTC, stevending1st commented on pages/activity/[name]/index.tsx
> +  return { props: { activity, teams, enrollmentStatus, myteam } };
改了一半

2022-09-25 18:26 UTC, TechQuery approved these changes

2022-09-25 18:27 UTC, merged